---
# Build Version
build_version: "0.1.0"

# Microservices release tags of docker images
datamigrator_ui_tag: "latest"
config_service_tag: "latest"
db_writer_service_tag: "latest"
jobs_service_tag: "latest"
reports_service_tag: "latest"
admin_service_tag: "latest"
keycloak_customizations_tag: "latest"
db_migrations_tag: "latest"
support_service_tag: "latest"

chart_names:
  - admin-service
  - config-service
  - db-writer
  - jobs-service
  - reports-service
  - datamigrator-ui
  - db-migrations
  - support-service

acr_registry: "{{ 'localhost:32000' if local_cluster is defined and local_cluster | bool else '' }}"

azure_client_id: "{{ lookup('env', 'ARM_CLIENT_ID') }}"
azure_client_secret: "{{ lookup('env', 'ARM_CLIENT_SECRET') }}"

vm_username: "datamigrator"
vm_uid: 1030
vm_gid: 1030

# Version management
microk8s_version: "1.32/stable"
microk8s_disable_snap_autoupdate: false

# Cluster CIDR Values
service_cidr: "10.152.183.0/24"
pod_network_cidr: "10.1.0.0/16"

# Plugin configuration
# microk8s_dns_resolvers: 8.8.8.8,8.8.4.4
# registry_size: 30Gi
microk8s_plugins:
  dns: true # CoreDNS
  host-access: false # Allow Pods connecting to Host services smoothly
  ingress: true # Ingress controller for external access
  metrics-server: true # K8s Metrics Server for API access to service metrics
  rbac: true # Role-Based Access Control for authorisation
  hostpath-storage: true # Storage class; allocates storage from host directory
  registry: false # Private image registry exposed on localhost:32000
  dashboard: true # The Kubernetes dashboard
  ambassador: false # Ambassador API Gateway and Ingress
  cilium: false # SDN, fast with full network policy
  fluentd: false # Elasticsearch-Fluentd-Kibana logging and monitoring
  gpu: false # Automatic enablement of Nvidia CUDA
  helm: true # Helm 2 - the package manager for Kubernetes
  helm3: true # Helm 3 - Kubernetes package manager
  istio: false # Core Istio service mesh services
  jaeger: false # Kubernetes Jaeger operator with its simple config
  knative: false # The Knative framework on Kubernetes.
  kubeflow: false # Kubeflow for easy ML deployments
  linkerd: false # Linkerd is a service mesh for Kubernetes and other frameworks
  metallb: false # Loadbalancer for your Kubernetes cluster
  multus: false # Multus CNI enables attaching multiple network interfaces to pods
  prometheus: false # Prometheus operator for monitoring and logging
  traefik: false # another ingress
  portainer: false # Container management dashboard
  keda: false # Kubernetes Event-driven Autoscaling operator.
  kata: false # A secure container runtime with lightweight virtual machines
  openebs: false # openebs storage
  openfaas: false # serverless

helm3_repositories:
  - name: stable
    url: https://charts.helm.sh/stable

# users to make members of microk8s group
users:
  - datamigrator

# for setting up custom certificate request.  Set to template name to enable
#microk8s_csr_template: null

# when /snap/bin is not in the PATH
microk8s_bin_path: ""

ports_to_open:
  - tcp 22
  - tcp 80
  - tcp 8080
  - tcp 53
  - udp 53
  - udp 123
  - tcp 179
  - tcp 443
  - tcp 2379:2381
  - tcp 4318
  - tcp 5432
  - tcp 6379
  - tcp 6443
  - tcp 6781:6784
  - udp 6781:6784
  - tcp 7233
  - tcp 8090:8091
  - udp 8472
  - tcp 9153
  - tcp 10248:10260
  - udp 4789
  - tcp 5473
  - tcp 8443
  - udp 8472
  - tcp 9099
  - tcp 27017:27019
  - tcp 30000:65535
  - tcp 9000:9005
  - tcp 16443
  - tcp 9091

postgres_version: 16.2.5
postgres_data_volume_size: 30Gi

openbao_version: 0.9.0
openbao_data_volume_size: 8Gi

keycloak_version: 24.6.7

#redis_version: 11.4.1
redis_version: 20.8.0
redis_data_volume_size: 30Gi

temporal_version: 0.57.0

grafana_version: 11.4.7
grafana_data_volume_size: 10Gi
lokistack_version: 6.27.0
loki_data_volume_size: 10Gi

prometheus_version: 27.5.1
prometheus_alertmanager_data_volume_size: 10Gi
prometheus_data_volume_size: 10Gi

fluentbit_version: 0.48.8
fluentbit_data_volume_size: 10Gi

fluentd_version: 0.5.2
fluentd_data_volume_size: 10Gi

otel_collector_version: 0.125.0