---
- name: Copy cloud-init configuration
  become: yes
  copy:
    src: ./templates/cloud-init.j2
    dest: /etc/cloud/cloud.cfg.d/00-datamigrator-hostname-init.cfg
    owner: root
    group: root
    mode: "0644"

- name: Copy boot script for microk8s
  become: yes
  template:
    src: ./templates/boot-script.j2
    dest: /opt/datamigrator/bin/microk8s-boot.sh
    owner: root
    group: root
    mode: "0755"

- name: Copy admin-entry configmap for Keycloak realm initialization
  become: yes
  template:
    src: ../../post-install/templates/admin-entry-configmap.j2
    dest: $HOME/admin-entry-configmap.yaml
    owner: root
    group: root
    mode: "0644"

- name: Copy admin-entry job for Keycloak realm initialization
  become: yes
  template:
    src: ../../post-install/templates/admin-entry-job.j2
    dest: $HOME/admin-entry-job.yaml
    owner: root
    group: root
    mode: "0644"

- name: Copy systemd service file for boot script
  become: yes
  template:
    src: ./templates/microk8s-boot-service.j2
    dest: /etc/systemd/system/boot-microk8s.service
    owner: root
    group: root
    mode: "0644"

- name: Copy OpenBao unseal script
  become: yes
  copy:
    src: ./templates/openbao-unseal.j2
    dest: /opt/datamigrator/bin/unseal.sh
    owner: root
    group: root
    mode: "0755"

- name: Copy systemd service file for OpenBao unseal
  become: yes
  template:
    src: ./templates/openbao-unseal-service.j2
    dest: /etc/systemd/system/openbao-unseal.service
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd daemon
  become: yes
  command: systemctl daemon-reload

- name: Enable the OpenBao unseal service
  become: yes
  ansible.builtin.systemd_service:
    name: openbao-unseal.service
    enabled: yes

- name: Enable the microk8s boot service
  become: yes
  ansible.builtin.systemd_service:
    name: boot-microk8s.service
    enabled: yes
