// Temporal Workflow Timeout Constants
export const WORKFLOW_TIMEOUTS = {
    PARENT_WORKFLOW_EXECUTION_TIMEOUT: '24h',
    PARENT_WORKFLOW_RUN_TIMEOUT: '24h',
    CHILD_WORKFLOW_EXECUTION_TIMEOUT: '19h',
    CHILD_WORKFLOW_RUN_TIMEOUT: '19h',
    ACTIVITY_TIMEOUT: '6h',
} as const;

export const WORKFLOW_EXECUTION_TIMEOUT_SECONDS = 60;
