---
- name: Creates keycloak directory
  become: yes
  file:
    path: $HOME/keycloak
    state: directory

- name: get passwords for keycloak from openbao
  become: yes
  shell: |
    export KEYCLOAK_ADMIN_PASSWORD=$(kubectl exec -ti openbao-0 -n openbao -- bao kv get -format=json /secrets/keycloak-secrets/keycloak-creds | jq -r .data.KEYCLOAK_ADMIN_PASSWORD)
    export KEYCLOAK_POSTGRES_PASSWORD=$(kubectl exec -ti openbao-0 -n openbao -- bao kv get -format=json /secrets/postgres-secrets/postgres-creds | jq -r .data.KEYCLOAK_POSTGRES_PASSWORD)
    echo "KEYCLOAK_POSTGRES_PASSWORD:$KEYCLOAK_POSTGRES_PASSWORD"
    echo "KEYCLOAK_ADMIN_PASSWORD:$KEYCLOAK_ADMIN_PASSWORD"
  register: keycloak_passwords

- name: Set passwords as facts
  set_fact:
    keycloak_admin_password_base64: "{{ (keycloak_passwords.stdout_lines | select('match', 'KEYCLOAK_ADMIN_PASSWORD:.*') | map('regex_replace', 'KEYCLOAK_ADMIN_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"
    keycloak_postgres_password_base64: "{{ (keycloak_passwords.stdout_lines | select('match', 'KEYCLOAK_POSTGRES_PASSWORD:.*') | map('regex_replace', 'KEYCLOAK_POSTGRES_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"

- name: Keycloak namespace
  become: yes
  template: src=./templates/keycloak-namespace.j2 dest=$HOME/keycloak/keycloak-namespace.yaml

- name: keycloak-values template
  become: yes
  template: src=./templates/keycloak-values.j2 dest=$HOME/keycloak/keycloak-values.yaml

- name: keycloak-secret template
  become: yes
  template: src=./templates/keycloak-secret.j2 dest=$HOME/keycloak/keycloak-secret.yaml

- name: remove previous installation
  become: yes
  shell: |
    helm delete keycloak --namespace "keycloak"
    kubectl delete -f $HOME/keycloak/keycloak-secret.yaml
    kubectl delete -f $HOME/keycloak/keycloak-namespace.yaml
  when: keycloak_uninstall is defined
  args:
    chdir: $HOME

- name: setup namespace
  become: yes
  shell: |
    kubectl apply -f $HOME/keycloak/keycloak-namespace.yaml
    kubectl apply -f $HOME/keycloak/keycloak-secret.yaml
  args:
    chdir: $HOME

- name: Download Keycloak Helm chart tarball
  become: yes
  shell: |
    helm pull oci://registry-1.docker.io/bitnamicharts/keycloak --version "{{ keycloak_version }}" --destination $HOME/keycloak
  args:
    executable: /bin/bash
  register: helm_download
  when: local_cluster is not defined

- name: debug output for Helm chart download
  ansible.builtin.debug:
    msg: "Helm chart download: stdout: {{ helm_download.stdout_lines | default([]) }}"
  when: local_cluster is not defined

- name: Deploy Keycloak and verify deployment
  block:
    - name: Deploy keycloak helm chart
      become: yes
      shell: |
        helm upgrade --install keycloak oci://registry-1.docker.io/bitnamicharts/keycloak -f $HOME/keycloak/keycloak-values.yaml --version "{{ keycloak_version }}" --namespace "keycloak"
        exit 0
      args:
        executable: /bin/bash
      register: SHELL_STDOUT

    - name: debug output
      ansible.builtin.debug:
        msg: "Kubectl deployment(keycloak): stderr: {{ SHELL_STDOUT.stderr_lines }} stdout: {{ SHELL_STDOUT.stdout_lines }}"

    - name: Wait for 20 seconds before waiting for pods to come up
      ansible.builtin.pause:
        seconds: 20

    - name: wait for pods to come up
      become: yes
      shell: kubectl wait --namespace="keycloak" --for=condition=Ready pod --all
      register: kubectl_get_pods
      retries: 10
      delay: 25
      until: kubectl_get_pods.rc == 0

    - name: debug output
      ansible.builtin.debug:
        msg: "Get pods (keycloak): {{ kubectl_get_pods.stdout | split('\n') }}"

    - name: Check Keycloak pod status
      shell: kubectl get pods -n keycloak
      register: pod_status

    - debug:
        var: pod_status.stdout

    - name: Delete keycloak directory
      become: yes
      file:
        path: $HOME/keycloak
        state: absent
  when: local_cluster is defined
  
  