appName: "db-writer"
kubeApiVersion: "apps/v1"
replicaCount: 1
name: datamigrate

image:
  repository: db-writer

annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "datamigrate-role"
    vault.hashicorp.com/agent-inject-secret-postgres.env: "secrets/postgres-secrets/postgres-creds"
    vault.hashicorp.com/agent-inject-secret-rabbitmq.env: "secrets/rabbitmq-secrets/rabbitmq-creds"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/agent-inject-template-postgres.env: |
      {{- with secret "secrets/postgres-secrets/postgres-creds" -}}
      export DB_USER="{{ .Data.POSTGRES_DMADMIN_USER }}"
      export DB_PASSWORD="{{ .Data.POSTGRES_DMADMIN_PASSWORD }}"
      {{- end }}
    vault.hashicorp.com/agent-inject-template-rabbitmq.env: |
      {{- with secret "secrets/rabbitmq-secrets/rabbitmq-creds" -}}
      export RABBITMQ_URLS=amqp://{{ .Data.RABBITMQ_USERNAME }}:{{ .Data.RABBITMQ_PASSWORD }}@rabbitmq.rabbitmq.svc.cluster.local:5672
      {{- end }}
    
serviceAccountName: datamigrate-vault-sa

args: 
  - "--source-vault"

imagePullSecrets: azure-dev-acr-creds

env:
  - name: MY_HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: APP_PORT
    value: "3000"
  - name: APP_HOST
    value: "$(MY_HOST_IP)"
  - name: DB_PORT
    value: "5432"
  - name: DB_HOST
    value: "postgres-postgresql.postgres.svc.cluster.local"
  # - name: DB_USER # from secret
  #   value: ""
  # - name: DB_PASSWORD # from secret
  #   value: ""
  # - name: RABBITMQ_URLS # from secret
  #   value: ""
  - name: DB_NAME
    value: "datamigrate"
  - name: SCHEMA
    value: "migrateadmin"
  - name: RABBITMQ_INVENTORY_QUEUE
    value: "inventory"
  - name: RABBITMQ_REPORTS_QUEUE
    value: "reports-queue"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000