apiVersion: v2
name: datamigrator
version: 0.1.0
dependencies:
  - name: admin-service
    version: 0.1.0
  - name: config-service
    version: 0.1.0
  - name: db-writer
    version: 0.1.0
  - name: jobs-service
    version: 0.1.0
  - name: reports-service
    version: 0.1.0
  - name: datamigrator-ui
    version: 0.1.0
