---
- name: 5.1. Configure user on the VM
  user:
    name: '{{ vm_username }}'
    state: present
  register: user_info

- name: 5.2. Transform user_home into a dictionary
  set_fact:
    user_info_dict: "{{ {vm_username: user_info} }}"

- name: 5.3. Add user to group
  user: 
    name: "{{ vm_username }}"
    groups: "microk8s"
    append: yes
  changed_when: true

- name: 5.4. Create .kube folder for the user
  become: yes
  file:
    path: "{{ user_info_dict[vm_username]['home'] }}/.kube"
    state: directory
    owner: '{{ vm_username }}'
    group: '{{ vm_username }}'
    mode: 0750

- name: 5.5. Create kubectl config
  become: yes
  changed_when: true
  shell: microk8s config > {{ user_info_dict[vm_username]['home'] }}/.kube/config
  args:
    executable: /bin/bash

- name: 5.5.1 Copy kubectl config to local machine
  fetch:
    src: "{{ user_info_dict[vm_username]['home'] }}/.kube/config"
    dest: "~/.kube/microk8s.config"
    flat: yes
  when: local_cluster is defined

- name: 5.6. Reaffirm permission on files
  become: yes
  file:
    path: "{{ user_info_dict[vm_username]['home'] }}/.kube"
    state: directory
    owner: '{{ vm_username }}'
    group: '{{ vm_username }}'
    recurse: yes
    mode: 0750

- name: 5.7. Add helm repository to user
  become: yes
  shell: "helm repo add {{ item.name }} {{ item.url }}"
  args:
    executable: /bin/bash
  with_items: "{{ helm3_repositories }}"
  when: microk8s_plugins.helm3

- name: 5.8. Update helm repos
  become: yes
  shell: "helm repo update"
  args:
    executable: /bin/bash
  changed_when: true
  when: microk8s_plugins.helm3
