appName: "datamigrator-ui"
kubeApiVersion: "apps/v1"
replicaCount: 1

image:
  repository: ndm-datamigrator-ui

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/role: "datamigrator-role"
  vault.hashicorp.com/agent-inject-secret-keycloak.env: "secrets/keycloak-secrets/keycloak-creds"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-template-keycloak.env: |
    {{- with secret "secrets/keycloak-secrets/keycloak-creds" -}}
    export VITE_KEYCLOAK_CLIENT_SECRET="{{ .Data.KEYCLOAK_CLIENT_SECRET }}"
    {{- end }}

serviceAccountName: datamigrator-openbao-sa

args:
  - "--source-vault"

imagePullSecrets: azure-dev-acr-creds

env:
  - name: MY_HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: VITE_PORT
    value: "3111"
  - name: VITE_HARD_CODE_ACCOUNT_ID
    value: "753975cb-2f97-4230-b632-6815515a7d0d"
  - name: VITE_BASE_URL
    value: "/api/v1"
  - name: VITE_USER_ID
    value: "66d6da7b559c0a9b7077909b"
  - name: VITE_KEYCLOAK_HOST
    value: "https://$(MY_HOST_IP)/keycloak"
  - name: VITE_KEYCLOAK_REALM
    value: "datamigrator"
  - name: VITE_KEYCLOAK_CLIENT
    value: "datamigrator-client"
  - name: VITE_KEYCLOAK_AUTHORITY
    value: "https://$(MY_HOST_IP)/keycloak/realms/datamigrator"
  - name: VITE_KEYCLOAK_GRANT_TYPE
    value: "authorization_code"
  - name: VITE_KEYCLOAK_CLIENT_ID
    value: "datamigrator-client"

  # - name: VITE_KEYCLOAK_CLIENT_SECRET
  #   value: ""

  - name: VITE_KEYCLOAK_REDIRECT_URI
    value: "https://$(MY_HOST_IP)/home"
  - name: VITE_KEYCLOAK_RESPONSE_TYPE
    value: "code"
  - name: VITE_KEYCLOAK_POST_LOGOUT_REDIRECT_URI
    value: "https://$(MY_HOST_IP)/home"
  - name: VITE_SESSION_KEY
    value: "oidc.user:https://$(MY_HOST_IP)/keycloak/realms/datamigrator:datamigrator-client"
  - name: VITE_APP_ADMIN_ROLE_NAME
    value: "App Admin"
  - name: VITE_API_LIMIT
    value: "1000"

  - name: VITE_ADMIN_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3000"
  - name: VITE_CONFIG_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3000"
  - name: VITE_JOBS_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3000"
  - name: VITE_REPORTS_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3006"
  - name: VITE_FILE_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3000"

  - name: VITE_ADMIN_SERVICE_URL
    value: "/api/v1"
  - name: VITE_CONFIG_SERVICE_URL
    value: "/api/v1"
  - name: VITE_JOBS_SERVICE_URL
    value: "/api/v1"
  - name: VITE_WORKERS_SERVICE_URL
    value: "/api/v1/workers"
  - name: VITE_REPORTS_SERVICE_URL
    value: "/api/v1/report"
  - name: VITE_FILE_SERVICE_URL
    value: "/api/v1"
  - name: VITE_TIME_INTERVAL
    value: "30000"
  - name: VITE_GRAFANA_URL
    value: "https://$(MY_HOST_IP)/grafana"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  ingressClassName: public
  userDefinedAnnotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    enabled: false
  host: ""
