---
- name: Creates temporal directory
  become: yes
  file:
    path: $HOME/temporal
    state: directory

- name: Generate random password for temporal
  become: yes
  shell: |
    export TEMPORAL_POSTGRES_PASSWORD=$(kubectl exec -ti openbao-0 -n openbao -- bao kv get -format=json /secrets/postgres-secrets/postgres-creds | jq -r .data.TEMPORAL_POSTGRES_PASSWORD)
    echo "TEMPORAL_POSTGRES_PASSWORD:$TEMPORAL_POSTGRES_PASSWORD"
  args:
    executable: /bin/bash
  register: temporal_passwords

- name: Set Base64-encoded password as fact
  set_fact:
    temporal_db_password: "{{ (temporal_passwords.stdout_lines | select('match', 'TEMPORAL_POSTGRES_PASSWORD:.*') | map('regex_replace', 'TEMPORAL_POSTGRES_PASSWORD:(.*)', '\\1') | list | first) }}"
    temporal_db_password_base64: "{{ (temporal_passwords.stdout_lines | select('match', 'TEMPORAL_POSTGRES_PASSWORD:.*') | map('regex_replace', 'TEMPORAL_POSTGRES_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"

- name: temporal-namespace template
  become: yes
  template: src=./templates/temporal-namespace.j2 dest=$HOME/temporal/temporal-namespace.yaml

- name: temporal-secret template
  become: yes
  template: src=./templates/temporal-secret.j2 dest=$HOME/temporal/temporal-secret.yaml

- name: temporal-values template
  become: yes
  template: src=./templates/temporal-values.j2 dest=$HOME/temporal/temporal-values.yaml

- name: temporal-peerauthentication template
  become: yes
  template: src=./templates/temporal-peerauthentication.yaml dest=$HOME/temporal/temporal-peerauthentication.yaml

- name: Cleanup service account
  become: yes
  shell: |
    kubectl delete serviceaccount -n temporal temporal-sa
  when: temporal_uninstall is defined

- name: remove previous installation
  become: yes
  shell: |
    helm delete temporal --namespace "temporal"
    kubectl delete pvc --all --namespace "temporal"
    kubectl delete -f $HOME/temporal/temporal-secret.yaml
    kubectl delete -f $HOME/temporal/temporal-namespace.yaml
  when: temporal_uninstall is defined
  args:
    chdir: $HOME

- name: setup namespace and secret for temporal
  become: yes
  shell: |
    kubectl apply -f $HOME/temporal/temporal-namespace.yaml
    kubectl apply -f $HOME/temporal/temporal-secret.yaml
    kubectl apply -f $HOME/temporal/temporal-peerauthentication.yaml
  args:
    chdir: $HOME

- name: Create service account
  become: yes
  shell: |
    kubectl create serviceaccount temporal-sa -n temporal

- name: Deploy temporal helm chart
  become: yes
  shell: |
    helm upgrade --install --repo https://go.temporal.io/helm-charts -f $HOME/temporal/temporal-values.yaml temporaltest temporal --version "{{ temporal_version }}" --namespace "temporal"
    exit 0
  args:
    executable: /bin/bash
  register: SHELL_STDOUT

- name: debug output
  ansible.builtin.debug:
    msg: "Helm Install (temporal): stderr: {{ SHELL_STDOUT.stderr_lines }} stdout: {{ SHELL_STDOUT.stdout_lines }}"

- name: Wait for 150 seconds before waiting for pods to come up
  ansible.builtin.pause:
    seconds: 150

- name: Wait for pods to come up and handle failure
  block:
    - name: Wait for pods to come up
      become: yes
      shell: |
        kubectl wait --namespace="temporal" --for=condition=Ready pod \
        --selector='!job-name' --field-selector=status.phase!=Succeeded --timeout=120s && \
        kubectl wait --namespace="temporal" --for=condition=complete job --all --timeout=120s
      register: kubectl_get_pods
      retries: 10
      delay: 20
      until: kubectl_get_pods.rc == 0
  rescue:
    - name: Fetch and display pod logs
      become: yes
      shell: |
        for pod in $(kubectl get pods -n temporal -o jsonpath='{.items[*].metadata.name}'); do
          echo "Logs for pod: $pod"
          kubectl logs -n temporal $pod --all-containers=true
          echo "----------------------------------------"
        done
      register: pod_logs
    - name: Display pod logs
      ansible.builtin.debug:
        msg: "{{ pod_logs.stdout }}"
    - name: Fail the play due to pod readiness failure
      fail:
        msg: "Pods did not become ready within the expected time frame."

- name: debug output
  ansible.builtin.debug:
    msg: "Get pods (temporal): {{ kubectl_get_pods.stdout | split('\n') }}"

- name: Delete temporal directory
  become: yes
  file:
    path: $HOME/temporal
    state: absent
