export enum Pattern {
  DISCOVERY_COMPLETED = "discovery-completed",
}

export enum ReportType {
  COC = "COC",
  DISCOVERY = "DISCOVER",
  JOBS_REPORT = "JOBS_REPORT",
}

export enum ReportHeaders {
  FILE_SERVER = "Config Name",
  PATH = "Path",
  SHARED = "Shared",
  EXPORTED = "Exported",
  SHARES = "Shares",
  NUMBER_OF_SHARES = "Number of Shares",

  EXPORTS = "Exports",
  NUMBER_OF_EXPORTS = "Number of Exports",

  SCAN_STATUS = "Status",
  SCAN_PROTOCOL = "Protocol",
  SCAN_TIME = "Total Time",
  SCAN_ERRORS = "Scan Errors",
  SCANNED_CAPACITY = "Scanned Capacity",
  SCANNED_ITEM_COUNT = "Scanned Item Count",

  ITEM_COUNT_FILE = "Item Count with Item Type: File",
  ITEM_COUNT_DIRECTORY = "Item Count with Item Type: Directory",
  ITEM_COUNT_SYMLINK = "Item Count with Item Type: Symbolic link",

  FILE_COUNT_CREATION_FUTURE = "File Count with Creation Time future",
  FILE_COUNT_CREATION_0_1_WK = "File Count with Creation Time 0-1 wk",
  FILE_COUNT_CREATION_1_WK_1_MO = "File Count with Creation Time 1 wk - 1 mo",
  FILE_COUNT_CREATION_1_3_MO = "File Count with Creation Time 1-3 mo",
  FILE_COUNT_CREATION_3_6_MO = "File Count with Creation Time 3-6 mo",
  FILE_COUNT_CREATION_6_12_MO = "File Count with Creation Time 6-12 mo",
  FILE_COUNT_CREATION_1_2_YR = "File Count with Creation Time 1-2 yr",
  FILE_COUNT_CREATION_2_3_YR = "File Count with Creation Time 2-3 yr",
  FILE_COUNT_CREATION_3_4_YR = "File Count with Creation Time 3-4 yr",
  FILE_COUNT_CREATION_4_5_YR = "File Count with Creation Time 4-5 yr",
  FILE_COUNT_CREATION_5_6_YR = "File Count with Creation Time 5-6 yr",
  FILE_COUNT_CREATION_6_7_YR = "File Count with Creation Time 6-7 yr",
  FILE_COUNT_CREATION_7_8_YR = "File Count with Creation Time 7-8 yr",
  FILE_COUNT_CREATION_8_9_YR = "File Count with Creation Time 8-9 yr",
  FILE_COUNT_CREATION_9_10_YR = "File Count with Creation Time 9-10 yr",
  FILE_COUNT_CREATION_10_PLUS_YR = "File Count with Creation Time 10+ yr",

  CAPACITY_CREATION_FUTURE = "Capacity with Creation Time future",
  CAPACITY_CREATION_0_1_WK = "Capacity with Creation Time 0-1 wk",
  CAPACITY_CREATION_1_WK_1_MO = "Capacity with Creation Time 1 wk - 1 mo",
  CAPACITY_CREATION_1_3_MO = "Capacity with Creation Time 1-3 mo",
  CAPACITY_CREATION_3_6_MO = "Capacity with Creation Time 3-6 mo",
  CAPACITY_CREATION_6_12_MO = "Capacity with Creation Time 6-12 mo",
  CAPACITY_CREATION_1_2_YR = "Capacity with Creation Time 1-2 yr",
  CAPACITY_CREATION_2_3_YR = "Capacity with Creation Time 2-3 yr",
  CAPACITY_CREATION_3_4_YR = "Capacity with Creation Time 3-4 yr",
  CAPACITY_CREATION_4_5_YR = "Capacity with Creation Time 4-5 yr",
  CAPACITY_CREATION_5_6_YR = "Capacity with Creation Time 5-6 yr",
  CAPACITY_CREATION_6_7_YR = "Capacity with Creation Time 6-7 yr",
  CAPACITY_CREATION_7_8_YR = "Capacity with Creation Time 7-8 yr",
  CAPACITY_CREATION_8_9_YR = "Capacity with Creation Time 8-9 yr",
  CAPACITY_CREATION_9_10_YR = "Capacity with Creation Time 9-10 yr",
  CAPACITY_CREATION_10_PLUS_YR = "Capacity with Creation Time 10+ yr",

  FILE_COUNT_MODIFICATION_FUTURE = "File Count With Modification Time: future",
  FILE_COUNT_MODIFICATION_0_1_WK = "File Count With Modification Time: 0-1 wk",
  FILE_COUNT_MODIFICATION_1_WK_1_MO = "File Count With Modification Time: 1 wk - 1 mo",
  FILE_COUNT_MODIFICATION_1_3_MO = "File Count With Modification Time: 1-3 mo",
  FILE_COUNT_MODIFICATION_3_6_MO = "File Count With Modification Time: 3-6 mo",
  FILE_COUNT_MODIFICATION_6_12_MO = "File Count With Modification Time: 6-12 mo",
  FILE_COUNT_MODIFICATION_1_2_YR = "File Count With Modification Time: 1-2 yr",
  FILE_COUNT_MODIFICATION_2_3_YR = "File Count With Modification Time: 2-3 yr",
  FILE_COUNT_MODIFICATION_3_4_YR = "File Count With Modification Time: 3-4 yr",
  FILE_COUNT_MODIFICATION_4_5_YR = "File Count With Modification Time: 4-5 yr",
  FILE_COUNT_MODIFICATION_5_6_YR = "File Count With Modification Time: 5-6 yr",
  FILE_COUNT_MODIFICATION_6_7_YR = "File Count With Modification Time: 6-7 yr",
  FILE_COUNT_MODIFICATION_7_8_YR = "File Count With Modification Time: 7-8 yr",
  FILE_COUNT_MODIFICATION_8_9_YR = "File Count With Modification Time: 8-9 yr",
  FILE_COUNT_MODIFICATION_9_10_YR = "File Count With Modification Time: 9-10 yr",
  FILE_COUNT_MODIFICATION_10_PLUS_YR = "File Count With Modification Time 10+ yr",

  CAPACITY_MODIFICATION_FUTURE = "Capacity With Modification Time: future",
  CAPACITY_MODIFICATION_0_1_WK = "Capacity With Modification Time: 0-1 wk",
  CAPACITY_MODIFICATION_1_WK_1_MO = "Capacity With Modification Time: 1 wk - 1 mo",
  CAPACITY_MODIFICATION_1_3_MO = "Capacity With Modification Time: 1-3 mo",
  CAPACITY_MODIFICATION_3_6_MO = "Capacity With Modification Time: 3-6 mo",
  CAPACITY_MODIFICATION_6_12_MO = "Capacity With Modification Time: 6-12 mo",
  CAPACITY_MODIFICATION_1_2_YR = "Capacity With Modification Time: 1-2 yr",
  CAPACITY_MODIFICATION_2_3_YR = "Capacity With Modification Time: 2-3 yr",
  CAPACITY_MODIFICATION_3_4_YR = "Capacity With Modification Time: 3-4 yr",
  CAPACITY_MODIFICATION_4_5_YR = "Capacity With Modification Time: 4-5 yr",
  CAPACITY_MODIFICATION_5_6_YR = "Capacity With Modification Time: 5-6 yr",
  CAPACITY_MODIFICATION_6_7_YR = "Capacity With Modification Time: 6-7 yr",
  CAPACITY_MODIFICATION_7_8_YR = "Capacity With Modification Time: 7-8 yr",
  CAPACITY_MODIFICATION_8_9_YR = "Capacity With Modification Time: 8-9 yr",
  CAPACITY_MODIFICATION_9_10_YR = "Capacity With Modification Time: 9-10 yr",
  CAPACITY_MODIFICATION_10_PLUS_YR = "Capacity With Modification Time: 10+ yr",

  FILE_COUNT_ACCESS_FUTURE = "File Count with Access Time future",
  FILE_COUNT_ACCESS_0_1_WK = "File Count with Access Time 0-1 wk",
  FILE_COUNT_ACCESS_1_WK_1_MO = "File Count with Access Time 1 wk - 1 mo",
  FILE_COUNT_ACCESS_1_3_MO = "File Count with Access Time 1-3 mo",
  FILE_COUNT_ACCESS_3_6_MO = "File Count with Access Time 3-6 mo",
  FILE_COUNT_ACCESS_6_12_MO = "File Count with Access Time 6-12 mo",
  FILE_COUNT_ACCESS_1_2_YR = "File Count with Access Time 1-2 yr",
  FILE_COUNT_ACCESS_2_3_YR = "File Count with Access Time 2-3 yr",
  FILE_COUNT_ACCESS_3_4_YR = "File Count with Access Time 3-4 yr",
  FILE_COUNT_ACCESS_4_5_YR = "File Count with Access Time 4-5 yr",
  FILE_COUNT_ACCESS_5_6_YR = "File Count with Access Time 5-6 yr",
  FILE_COUNT_ACCESS_6_7_YR = "File Count with Access Time 6-7 yr",
  FILE_COUNT_ACCESS_7_8_YR = "File Count with Access Time 7-8 yr",
  FILE_COUNT_ACCESS_8_9_YR = "File Count with Access Time 8-9 yr",
  FILE_COUNT_ACCESS_9_10_YR = "File Count with Access Time 9-10 yr",
  FILE_COUNT_ACCESS_10_PLUS_YR = "File Count with Access Time 10+ yr",

  CAPACITY_ACCESS_FUTURE = "Capacity with Access Time future",
  CAPACITY_ACCESS_0_1_WK = "Capacity with Access Time 0-1 wk",
  CAPACITY_ACCESS_1_WK_1_MO = "Capacity with Access Time 1 wk - 1 mo",
  CAPACITY_ACCESS_1_3_MO = "Capacity with Access Time 1-3 mo",
  CAPACITY_ACCESS_3_6_MO = "Capacity with Access Time 3-6 mo",
  CAPACITY_ACCESS_6_12_MO = "Capacity with Access Time 6-12 mo",
  CAPACITY_ACCESS_1_2_YR = "Capacity with Access Time 1-2 yr",
  CAPACITY_ACCESS_2_3_YR = "Capacity with Access Time 2-3 yr",
  CAPACITY_ACCESS_3_4_YR = "Capacity with Access Time 3-4 yr",
  CAPACITY_ACCESS_4_5_YR = "Capacity with Access Time 4-5 yr",
  CAPACITY_ACCESS_5_6_YR = "Capacity with Access Time 5-6 yr",
  CAPACITY_ACCESS_6_7_YR = "Capacity with Access Time 6-7 yr",
  CAPACITY_ACCESS_7_8_YR = "Capacity with Access Time 7-8 yr",
  CAPACITY_ACCESS_8_9_YR = "Capacity with Access Time 8-9 yr",
  CAPACITY_ACCESS_9_10_YR = "Capacity with Access Time 9-10 yr",
  CAPACITY_ACCESS_10_PLUS_YR = "Capacity with Access Time 10+ yr",

  FILE_COUNT_FILE_SIZE_0_B = "File Count with File Size: 0B",
  FILE_COUNT_FILE_SIZE_0_8_KiB = "File Count with File Size: <8KiB",
  FILE_COUNT_FILE_SIZE_8_64_KiB = "File Count with File Size: 8-64KiB",
  FILE_COUNT_FILE_SIZE_64_KiB_1_MiB = "File Count with File Size: 64KiB-1MiB",
  FILE_COUNT_FILE_SIZE_1_10_MiB = "File Count with File Size: 1-10MiB",
  FILE_COUNT_FILE_SIZE_10_100_MiB = "File Count with File Size: 10-100MiB",
  FILE_COUNT_FILE_SIZE_100_MiB_1_GiB = "File Count with File Size: 100MiB-1GiB",
  FILE_COUNT_FILE_SIZE_1_PLUS_GiB = "File Count with File Size: 1+ GiB",

  CAPACITY_FILE_SIZE_0_B = "Capacity with File Size: 0B",
  CAPACITY_FILE_SIZE_0_8_KiB = "Capacity with File Size: <8KiB",
  CAPACITY_FILE_SIZE_8_64_KiB = "Capacity with File Size: 8-64 KiB",
  CAPACITY_FILE_SIZE_64_KiB_1_MiB = "Capacity with File Size: 64 KiB - 1 MiB",
  CAPACITY_FILE_SIZE_1_10_MiB = "Capacity with File Size: 1-10 MiB",
  CAPACITY_FILE_SIZE_10_100_MiB = "Capacity with File Size: 10-100 MiB",
  CAPACITY_FILE_SIZE_100_MiB_1_GiB = "Capacity with File Size: 100 MiB - 1 GiB",
  CAPACITY_FILE_SIZE_1_PLUS_GiB = "Capacity with File Size: 1+ GiB",

  LONGEST_FILE_NAMES = "Longest File Names",
  LONGEST_DIRECTORY_NAMES = "Longest Directory Names",
  LONGEST_FILE_PATHS = "Longest File Path",
  LONGEST_DIRECTORY_PATHS = "Longest Directory Path",
  BIGGEST_FILES = "Biggest File Names",
  BIGGEST_DIRECTORIES_WITH_COUNT = "Biggest Directory With Count",
  BIGGEST_DIRECTORIES_WITH_CAPACITY = "Biggest Directory With Capacity",
  TOP_FILE_EXTENSIONS = "Top File Extensions (with file count and Capacity)",
  CASE_SENSITIVITY_CONFLICTS = "Case Sensitivity Conflicts",
  FILE_NAME_TRAILING_SPACES = "Files without extensions and trailing spaces",
}
