---
- name: Ensure destination directories exist
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"
    mode: '0755'
  loop:
    - /opt/datamigrator
    - /opt/datamigrator/bin
    - /var/log/datamigrator

- name: Copy binary file to remote server
  become: yes
  ansible.builtin.copy:
    src: "{{ local_binary_path }}"
    dest: "{{ remote_binary_path }}"
    mode: '0755'

- name: Make the binary file executable
  become: yes
  ansible.builtin.file:
    path: "{{ remote_binary_path }}"
    mode: '0755'

- name: Update systemd service file with the latest binary
  become: yes
  ansible.builtin.template:
    src: ./templates/worker.service.j2
    dest: /etc/systemd/system/datamigrator-worker.service
    owner: root
    group: root
    mode: '0644'

- name: Copy worker-register.j2 to /opt/datamigrator/bin/
  become: yes
  copy:
    src: ./templates/worker-register.j2
    dest: /opt/datamigrator/bin/worker_register.sh
    mode: '0755'
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"


- name: Copy worker env to /opt/datamigrator/conf/
  become: yes
  copy:
    src: ./templates/worker.env.j2
    dest: /opt/datamigrator/conf/worker.env
    mode: '0644'
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"

- name: Reload systemd daemon
  become: yes
  ansible.builtin.command: systemctl daemon-reload

- name: Enable the datamigrator worker service
  become: yes
  systemd:
    name: datamigrator-worker.service
    enabled: yes
