---
- name: Ensure destination directories exist
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"
    mode: '0755'
  loop:
    - { path: "/opt/datamigrator" }
    - { path: "/opt/datamigrator/bin" }
    - { path: "/opt/datamigrator/binary" }
    - { path: "/opt/datamigrator/conf" }
    - { path: "/opt/datamigrator/logs" }
    - { path: "/var/log/datamigrator" }

- name: Copy binary file to remote server
  become: yes
  ansible.builtin.copy:
    src: "{{ local_binary_path }}"
    dest: "{{ remote_binary_path }}"
    mode: '0755'

- name: Make the binary file executable
  become: yes
  ansible.builtin.file:
    path: "{{ remote_binary_path }}"
    mode: '0755'

- name: Update systemd service file with the latest binary
  become: yes
  ansible.builtin.template:
    src: ./templates/worker.service.j2
    dest: /etc/systemd/system/datamigrator-worker.service
    owner: root
    group: root
    mode: '0644'

- name: Copy worker-register.j2 to /opt/datamigrator/bin/
  become: yes
  copy:
    src: ./templates/worker-register.j2
    dest: /opt/datamigrator/bin/worker_register.sh
    mode: '0755'
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"


- name: Copy worker env to /opt/datamigrator/conf/
  become: yes
  copy:
    src: ./templates/worker.env.j2
    dest: /opt/datamigrator/conf/worker.env
    mode: '0644'
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"

- name: Reload systemd daemon
  become: yes
  ansible.builtin.command: systemctl daemon-reload

- name: Disable the datamigrator worker service from starting on boot
  become: yes
  ansible.builtin.systemd_service:
    name: datamigrator-worker.service
    enabled: false
    state: stopped
