appName: "data-migrate-ui"
kubeApiVersion: "apps/v1"
replicaCount: 1

image:
  repository: data-migrate-ui

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "datamigrate-role"
  vault.hashicorp.com/agent-inject-secret-keycloak.env: "secrets/keycloak-secrets/keycloak-creds"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-template-keycloak.env: |
    {{- with secret "secrets/keycloak-secrets/keycloak-creds" -}}
    export NEXT_PUBLIC_KEYCLOAK_CLIENT_SECRET="{{ .Data.KEYCLOAK_CLIENT_SECRET }}"
    {{- end }}

serviceAccountName: datamigrate-vault-sa

args: 
  - "--source-vault"

imagePullSecrets: azure-dev-acr-creds

env:
  - name: MY_HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: NEXT_PUBLIC_PORT
    value: "3111"
  - name: NEXT_PUBLIC_HARD_CODE_ACCOUNT_ID
    value: "1419c156-f370-473a-b886-7d0b952e77e1"
  - name: NEXT_PUBLIC_BASE_URL
    value: "/api/v1"
  - name: NEXT_PUBLIC_USER_ID
    value: "66d6da7b559c0a9b7077909b"
  - name: NEXT_PUBLIC_KEYCLOAK_HOST
    value: "https://$(MY_HOST_IP)/keycloak"
  - name: NEXT_PUBLIC_KEYCLOAK_REALM
    value: "datamigrate"
  - name: NEXT_PUBLIC_KEYCLOAK_CLIENT
    value: "datamigrate-client"
  - name: NEXT_PUBLIC_KEYCLOAK_AUTHORITY
    value: "https://$(MY_HOST_IP)/keycloak/realms/datamigrate"
  - name: NEXT_PUBLIC_KEYCLOAK_GRANT_TYPE
    value: "authorization_code"
  - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
    value: "datamigrate-client"

  # - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_SECRET
  #   value: ""

  - name: NEXT_PUBLIC_KEYCLOAK_REDIRECT_URI
    value: "https://$(MY_HOST_IP)/home"
  - name: NEXT_PUBLIC_KEYCLOAK_RESPONSE_TYPE
    value: "code"
  - name: NEXT_PUBLIC_KEYCLOAK_POST_LOGOUT_REDIRECT_URI
    value: "https://$(MY_HOST_IP)/home"
  - name: NEXT_PUBLIC_SESSION_KEY
    value: "oidc.user:https://$(MY_HOST_IP)/keycloak/realms/datamigrate:datamigrate-client"
  - name: NEXT_PUBLIC_APP_ADMIN_ROLE_NAME
    value: "App Admin"
  - name: NEXT_PUBLIC_API_LIMIT
    value: "1000"

  - name: NEXT_PUBLIC_ADMIN_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3000"
  - name: NEXT_PUBLIC_CONFIG_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3000"
  - name: NEXT_PUBLIC_JOBS_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3000"
  - name: NEXT_PUBLIC_REPORTS_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3006"
  - name: NEXT_PUBLIC_FILE_SERVICE_ENDPOINT
    value: "http://127.0.0.1:3000"

  - name: NEXT_PUBLIC_ADMIN_SERVICE_URL
    value: "/api/v1"
  - name: NEXT_PUBLIC_CONFIG_SERVICE_URL
    value: "/api/v1"
  - name: NEXT_PUBLIC_JOBS_SERVICE_URL
    value: "/api/v1"
  - name: NEXT_PUBLIC_WORKERS_SERVICE_URL
    value: "/api/v1/workers"
  - name: NEXT_PUBLIC_REPORTS_SERVICE_URL
    value: "/api/v1/report"
  - name: NEXT_PUBLIC_FILE_SERVICE_URL
    value: "/api/v1"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  ingressClassName: public
  userDefinedAnnotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls:
    enabled: false
  host: ""