apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-config
  labels:
    app: {{ .Values.nameOverride }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  JWT_ALGORITHMS: {{ .Values.auth.jwtAlgorithms | quote }}
  JWT_ISSUER: {{ .Values.auth.jwtIssuer | quote }}
  JWT_AUDIENCE: {{ .Values.auth.jwtAudience | quote }}
  DATA_ROOT: {{ .Values.pvc.mountPath | quote }}
