---

- name: delete vault-data directory if uninstall flag is defined 
  file:
    path: /data/vault-data
    state: absent
    owner: 100
    group: 1000   
    mode: 0755
  when: vault_uninstall is defined

- name: create vault-data directory 
  file:
    path: /data/vault-data
    state: directory
    owner: 100
    group: 1000   
    mode: 0755