{
 "title": "Worker Logging Dashboard",
 "tags": [
  "Loki",
  "Worker"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Total Logs By Time / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"worker\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Logs By Level / $__interval",
   "type": "timeseries",
   "description": "How many logs of each level?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(detected_level) (\n  count_over_time({job=\"worker\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Recent Error Logs",
   "type": "logs",
   "description": "Show the latest errors on the dashboard",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"worker\"} | logfmt | label_format level=detected_level | level = `error`"
    }
   ]
  },
  {
   "title": "Worker Logs",
   "type": "logs",
   "description": "All the worker log content",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"worker\"} |= ``"
    }
   ]
  }
 ]
}