---
- name: Update apt package index
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure essential packages are installed
  apt:
    name:
      - nfs-common
      - smbclient
    state: present

# - name: 2.3. Ensure rpc-statd is enabled and running
#   systemd:
#     name: rpc-statd
#     enabled: yes
#     state: started
#     masked: no
- name: Copy systemd service file for boot script
  become: yes
  template:
    src: ./templates/start-rpc-statd-service.j2
    dest: /etc/systemd/system/start-rpc-statd.service
    owner: root
    group: root
    mode: "0644"

- name: Reload systemd daemon
  become: yes
  command: systemctl daemon-reload

- name: Enable the start rpc-statd service
  become: yes
  systemd:
    name: start-rpc-statd.service
    enabled: yes

- name: Set the hostname
  command: hostnamectl set-hostname datamigrator
