---
- name: Playbook for Linux
  become: true
  become_method: ansible.builtin.sudo
  debugger: never
  gather_facts: true
  hosts: default
  vars:
    ansible_python_interpreter: auto
    ansible_python_interpreter_fallback: ['python3.13', 'python3.12', 'python3.11', 'python3.10', 'python3.9', 'python3.8', '/usr/bin/python3', 'python3']
  roles:
    - { role:  ../roles/base-iso/base, tags: 'configure-base' }
    - { role:  ../roles/base-iso/users, tags: 'configure-users' }
    - { role:  ../roles/base-iso/configure, tags: 'configure-iso' }
