---
- name: Get the node name of the Packer VM
  become: yes
  command: hostname
  register: node_name

- name: Remove the Packer node from the MicroK8s cluster
  become: yes
  command: kubectl delete node "{{ node_name.stdout }}"
  register: delete_node_result

- name: Display the result of node deletion
  become: yes
  debug:
    msg: "{{ delete_node_result.stdout }}"

# - name: Configure kube-apiserver
#   become: yes
#   lineinfile:
#     path: /var/snap/microk8s/current/args/kube-apiserver
#     regexp: '^(--advertise-address|--bind-address).*'
#     line: "{{ item }}"
#     create: yes
#   with_items:
#     - "--advertise-address=127.0.0.1"
#     - "--bind-address=127.0.0.1"
#notify: Restart MicroK8s

# - name: Configure kube-controller-manager
#   become: yes
#   lineinfile:
#     path: /var/snap/microk8s/current/args/kube-controller-manager
#     regexp: '^--bind-address.*'
#     line: "--bind-address=127.0.0.1"
#     create: yes
#   #notify: Restart MicroK8s

# - name: Configure kube-scheduler
#   become: yes
#   lineinfile:
#     path: /var/snap/microk8s/current/args/kube-scheduler
#     regexp: '^--bind-address.*'
#     line: "--bind-address=127.0.0.1"
#     create: yes
#   #notify: Restart MicroK8s

# - name: Configure kube-proxy
#   become: yes
#   lineinfile:
#     path: /var/snap/microk8s/current/args/kube-proxy
#     regexp: '^(--bind-address|--healthz-bind-address|--nodeport-addresses).*'
#     line: "{{ item }}"
#     create: yes
#   with_items:
#     - "--bind-address=127.0.0.1"
#     - "--healthz-bind-address=127.0.0.1"
#     - "--nodeport-addresses=127.0.0.1"
#   #notify: Restart MicroK8s

# - name: Configure kubelet
#   become: yes
#   lineinfile:
#     path: /var/snap/microk8s/current/args/kubelet
#     regexp: '^(--address|--node-ip|--healthz-bind-address).*'
#     line: "{{ item }}"
#     create: yes
#   with_items:
#     - "--address=127.0.0.1"
#     - "--node-ip=127.0.0.1"
#     - "--healthz-bind-address=127.0.0.1"
#   notify: Restart MicroK8s

# - name: Configure Calico VXLAN interface
#   become: yes
#   replace:
#     path: /var/snap/microk8s/current/args/cni-network/cni.yaml
#     regexp: '^( +- name: IP_AUTODETECTION_METHOD\n +value: ).*'
#     replace: '\1"interface=lo"'
#   notify: Apply Calico Configuration

- name: Stop MicroK8s
  become: yes
  command: microk8s stop
  register: microk8s_stop_result
  changed_when: microk8s_stop_result.rc == 0

- name: Verify MicroK8s is stopped
  become: yes
  command: microk8s status
  register: microk8s_status

- name: Debug MicroK8s status output
  debug:
    var: microk8s_status.stdout

- name: Wipe containerd image store to reduce VM image size
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/snap/microk8s/common/var/lib/containerd/io.containerd.content.v1.content
    - /var/snap/microk8s/common/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs
    - /var/snap/microk8s/common/var/lib/containerd/io.containerd.metadata.v1.bolt
