---
- name: Vault kubernetes authorization enabling
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec vault-0 -n vault -- vault auth enable kubernetes
    KUBERNETES_PORT_443_TCP_ADDR=$(kubectl exec vault-0 -n vault -- printenv | grep KUBERNETES_PORT_443_TCP_ADDR | cut -f 2- -d "=" | tr -d " ")
    kubectl exec vault-0 -n vault -- vault write auth/kubernetes/config kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" 

- name: Vault secret enable on path
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    # Check if the secrets engine already exists
    secrets_exist=$(kubectl exec -ti vault-0 -n vault -- vault secrets list -format=json | jq '.["secrets/"]')

    if [ "null" = "$secrets_exist" ]; then
      kubectl exec -ti vault-0 -n vault -- vault secrets enable -path=secrets/ kv
    else
      echo "Secrets engine 'secrets/' is already enabled."
    fi  

- name: Vault policies 
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -i vault-0 -n vault -- vault policy write {{ item }}-policy - <<EOF
    path "secrets/{{ item }}-secrets/{{ item }}-creds" {
      capabilities = ["read"]
    }
    EOF
  with_items:
    - keycloak
    - postgres
    - rabbitmq
  
- name: Vault roles creation -- datamigrate
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
    bound_service_account_names={{ item }}-vault-sa \
    bound_service_account_namespaces=datamigrate \
    policies=keycloak-policy,postgres-policy,rabbitmq-policy \
    ttl=24h
  with_items:
    - datamigrate

- name: Vault roles creation -- keycloak
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
    bound_service_account_names={{ item }}-sa \
    bound_service_account_namespaces=datamigrate,keycloak \
    policies=keycloak-policy,postgres-policy \
    ttl=24h
  with_items:
    - keycloak
  
- name: Vault roles creation -- postgres
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
    bound_service_account_names={{ item }}-sa \
    bound_service_account_namespaces=datamigrate,postgres \
    policies=postgres-policy \
    ttl=24h
  with_items:
    - postgres
  
- name: Vault roles creation -- rabbitmq
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
    bound_service_account_names={{ item }}-sa \
    bound_service_account_namespaces=datamigrate,rabbitmq \
    policies=rabbitmq-policy \
    ttl=24h
  with_items:
    - rabbitmq

# - name: Vault roles creation
#   become: yes
#   become_user: "{{ vm_username }}"
#   shell: |
#     kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
#     bound_service_account_names={{ item }}-sa \
#     bound_service_account_namespaces=datamigrate,keycloak,postgres \
#     policies={{ item }}-policy \
#     ttl=24h
#   with_items:
#     - keycloak
#     - postgres

- name: Cleanup service account
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl delete serviceaccount -n keycloak keycloak-sa
    kubectl delete serviceaccount -n postgres postgres-sa
    kubectl delete serviceaccount -n rabbitmq rabbitmq-sa
    kubectl delete serviceaccount -n datamigrate datamigrate-vault-sa
  ignore_errors: yes
  when: vault_uninstall is defined

- name: Create service account
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl create namespace datamigrate
    kubectl create serviceaccount -n datamigrate datamigrate-vault-sa
    kubectl create serviceaccount -n keycloak keycloak-sa
    kubectl create serviceaccount -n postgres postgres-sa
    kubectl create serviceaccount -n rabbitmq rabbitmq-sa
  ignore_errors: yes

- name: Create acr pull secert
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl create secret docker-registry azure-dev-acr-creds \
        --namespace datamigrate \
        --docker-server={{ acr_registry }} \
        --docker-username={{ azure_client_id }} \
        --docker-password={{ azure_client_secret }}
  ignore_errors: yes

- name: Create Vault password policy file
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/password-policy.hcl.j2 dest=$HOME/vault/password-policy.hcl

- name: Create Vault password policy file
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl cp $HOME/vault/password-policy.hcl vault-0:/tmp/password-policy.hcl -n vault 

- name: Vault password policy 
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -i vault-0 -n vault -- vault write sys/policies/password/datamigrate policy=@/tmp/password-policy.hcl

- name: Generate password for postgres
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    export POSTGRES_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrate/generate | jq -r '.data.password')
    export POSTGRES_DMADMIN_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrate/generate | jq -r '.data.password')
    kubectl exec vault-0 -n vault -- vault kv put secrets/postgres-secrets/postgres-creds \
      POSTGRES_USER="postgres" \
      POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
      POSTGRES_DMADMIN_USER="dmadmin" \
      POSTGRES_DMADMIN_PASSWORD="${POSTGRES_DMADMIN_PASSWORD}"

- name: Generate Keycloak secrets
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    export KEYCLOAK_CLIENT_SECRET=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrate/generate | jq -r '.data.password')
    export KEYCLOAK_ADMIN_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrate/generate | jq -r '.data.password')
    kubectl exec vault-0 -n vault -- vault kv put secrets/keycloak-secrets/keycloak-creds \
      KEYCLOAK_CLIENT_SECRET="${KEYCLOAK_CLIENT_SECRET}" \
      KEYCLOAK_ADMIN_USER="kc-admin" \
      KEYCLOAK_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD}"
  
- name: Generate rabbitmq secrets
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    export RABBITMQ_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrate/generate | jq -r '.data.password')
    kubectl exec vault-0 -n vault -- vault kv put secrets/rabbitmq-secrets/rabbitmq-creds RABBITMQ_USERNAME="rabbitmq" RABBITMQ_PASSWORD="${RABBITMQ_PASSWORD}"