appName: "reports-service"
kubeApiVersion: "apps/v1"
replicaCount: 1

image:
  repository: ndm-reports-service

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/role: "datamigrator-role"
  vault.hashicorp.com/agent-inject-secret-postgres.env: "secrets/postgres-secrets/postgres-creds"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-template-postgres.env: |
    {{- with secret "secrets/postgres-secrets/postgres-creds" -}}
    export DB_USER="{{ .Data.POSTGRES_DMADMIN_USER }}"
    export DB_PASSWORD="{{ .Data.POSTGRES_DMADMIN_PASSWORD }}"
    {{- end }}

serviceAccountName: datamigrator-openbao-sa

args:
  - "--source-vault"

imagePullSecrets: azure-dev-acr-creds

env:
  - name: MY_HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: APP_PORT
    value: "3006"
  - name: APP_HOST
    value: "$(MY_HOST_IP)"

  - name: DB_HOST
    value: "postgresql.postgres.svc.cluster.local"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "datamigrator"
  - name: SCHEMA
    value: "datamigrator"
  - name: REPORT_DOWNLOAD_LOCATION
    value: "/reports"
  - name: KEYCLOAK_BASE_URL
    value: "http://keycloak.keycloak.svc.cluster.local:80/keycloak"
  - name: KEYCLOAK_REALM
    value: "datamigrator"
  - name: TEMPORAL_ADDRESS
    value: "temporaltest-frontend.temporal.svc.cluster.local:7233"
  # - name: DB_USER # from secret
  #   value: ""
  # - name: DB_PASSWORD # from secret
  #   value: ""
  - name: LOG_LEVEL
    value: "INFO"
  - name: LOG_DIR
    value: "/logs"
  - name: ERROR_LOGS_DOWNLOAD_LOCATION
    value: "/error-logs"
  - name: ASUP_ENDPOINT
    value: "https://support.netapp.com/put/AsupPut"
  - name: ASUP_SUPPORT_BUNDLE_ENDPOINT
    value: "https://stagesupport.netapp.com/put/AsupPut"
  - name: JSON_PAYLOAD_LIMIT
    value: "500mb"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3006

ingress:
  prefixPaths:
    - /api/v1/report
    - /api/v1/reports-docs
  userDefinedAnnotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  ingressClassName: public
  tls:
    enabled: false
  host: ""

persistentVolumes:
  - name: reports-volume
    mountPath: /reports
    hostPath: /data/reports
  - name: error-logs-volume
    mountPath: /error-logs
    hostPath: /data/error-logs
