---

- name: delete redis-data directory if uninstall flag is defined 
  become: yes
  file:
    path: /data/redis-data
    state: absent
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"   
    mode: 0755
  when: redis_uninstall is defined

- name: create redis-data directory 
  become: yes
  file:
    path: /data/redis-data
    state: directory
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"   
    mode: 0755


