---
- name: Vault kubernetes authorization enabling
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec vault-0 -n vault -- vault auth enable kubernetes
    KUBERNETES_PORT_443_TCP_ADDR=$(kubectl exec vault-0 -n vault -- printenv | grep KUBERNETES_PORT_443_TCP_ADDR | cut -f 2- -d "=" | tr -d " ")
    kubectl exec vault-0 -n vault -- vault write auth/kubernetes/config kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" 

- name: Vault secret enable on path
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    # Check if the secrets engine already exists
    secrets_exist=$(kubectl exec -ti vault-0 -n vault -- vault secrets list -format=json | jq '.["secrets/"]')

    if [ "null" = "$secrets_exist" ]; then
      kubectl exec -ti vault-0 -n vault -- vault secrets enable -path=secrets/ kv
    else
      echo "Secrets engine 'secrets/' is already enabled."
    fi  

- name: Vault policies 
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -i vault-0 -n vault -- vault policy write {{ item }}-policy - <<EOF
    path "secrets/{{ item }}-secrets/{{ item }}-creds" {
      capabilities = ["read"]
    }
    EOF
  with_items:
    - keycloak
    - postgres
    - rabbitmq
  
- name: Vault roles creation -- datamigrator
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
    bound_service_account_names={{ item }}-vault-sa \
    bound_service_account_namespaces=datamigrator \
    policies=keycloak-policy,postgres-policy,rabbitmq-policy \
    ttl=24h
  with_items:
    - datamigrator

- name: Vault roles creation -- keycloak
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
    bound_service_account_names={{ item }}-sa \
    bound_service_account_namespaces=datamigrator,keycloak \
    policies=keycloak-policy,postgres-policy \
    ttl=24h
  with_items:
    - keycloak
  
- name: Vault roles creation -- postgres
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
    bound_service_account_names={{ item }}-sa \
    bound_service_account_namespaces=datamigrator,postgres \
    policies=postgres-policy \
    ttl=24h
  with_items:
    - postgres
  
- name: Vault roles creation -- rabbitmq
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
    bound_service_account_names={{ item }}-sa \
    bound_service_account_namespaces=datamigrator,rabbitmq \
    policies=rabbitmq-policy \
    ttl=24h
  with_items:
    - rabbitmq

# - name: Vault roles creation
#   become: yes
#   become_user: "{{ vm_username }}"
#   shell: |
#     kubectl exec -ti vault-0 -n vault -- vault write auth/kubernetes/role/{{ item }}-role \
#     bound_service_account_names={{ item }}-sa \
#     bound_service_account_namespaces=datamigrator,keycloak,postgres \
#     policies={{ item }}-policy \
#     ttl=24h
#   with_items:
#     - keycloak
#     - postgres

- name: Create Vault password policy file
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/password-policy.hcl.j2 dest=$HOME/vault/password-policy.hcl

- name: Create Vault keycloak client policy file
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/keycloak-secret.hcl.j2 dest=$HOME/vault/keycloak-secret.hcl

- name: Create Vault password policy file
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl cp $HOME/vault/password-policy.hcl vault-0:/tmp/password-policy.hcl -n vault 

- name: Create Vault keycloak client policy file
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl cp $HOME/vault/keycloak-secret.hcl vault-0:/tmp/keycloak-secret.hcl -n vault 

- name: Vault password policy 
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl exec -i vault-0 -n vault -- vault write sys/policies/password/datamigrator policy=@/tmp/password-policy.hcl
    kubectl exec -i vault-0 -n vault -- vault write sys/policies/password/keycloak policy=@/tmp/keycloak-secret.hcl

- name: Generate password for postgres
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    export POSTGRES_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrator/generate | jq -r '.data.password')
    export POSTGRES_DMADMIN_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrator/generate | jq -r '.data.password')
    export KEYCLOAK_POSTGRES_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrator/generate | jq -r '.data.password')
    export LIQUIBASE_POSTGRES_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrator/generate | jq -r '.data.password')
    kubectl exec vault-0 -n vault -- vault kv put secrets/postgres-secrets/postgres-creds \
      POSTGRES_USER="postgres" \
      POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
      POSTGRES_DMADMIN_USER="dmadmin" \
      POSTGRES_DMADMIN_PASSWORD="${POSTGRES_DMADMIN_PASSWORD}" \
      KEYCLOAK_POSTGRES_USER="kcadmin" \
      KEYCLOAK_POSTGRES_PASSWORD="${KEYCLOAK_POSTGRES_PASSWORD}" \
      LIQUIBASE_POSTGRES_USER="liquibase" \
      LIQUIBASE_POSTGRES_PASSWORD="${LIQUIBASE_POSTGRES_PASSWORD}"


- name: Generate Keycloak secrets
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    export KEYCLOAK_CLIENT_SECRET=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/keycloak/generate | jq -r '.data.password')
    export KEYCLOAK_ADMIN_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrator/generate | jq -r '.data.password')
    kubectl exec vault-0 -n vault -- vault kv put secrets/keycloak-secrets/keycloak-creds \
      KEYCLOAK_CLIENT_SECRET="${KEYCLOAK_CLIENT_SECRET}" \
      KEYCLOAK_ADMIN_USER="kc-admin" \
      KEYCLOAK_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD}"
  
- name: Generate rabbitmq secrets
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    export RABBITMQ_PASSWORD=$(kubectl exec -i vault-0 -n vault -- vault read -format=json sys/policies/password/datamigrator/generate | jq -r '.data.password')
    kubectl exec vault-0 -n vault -- vault kv put secrets/rabbitmq-secrets/rabbitmq-creds RABBITMQ_USERNAME="rabbitmq" RABBITMQ_PASSWORD="${RABBITMQ_PASSWORD}"

- name: Delete vault directory
  become: yes
  become_user: "{{ vm_username }}"
  file:
    path: $HOME/vault
    state: absent
