---
- name: Creates postgres directory
  become: yes
  become_user: "{{ vm_username }}"
  file:
    path: $HOME/postgres
    state: directory

- name: generate random passwords for postgres
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    export POSTGRES_ROOT_PASSWORD=$(kubectl exec -ti vault-0 -n vault -- vault kv get -format=json /secrets/postgres-secrets/postgres-creds | jq -r .data.POSTGRES_PASSWORD)
    export DMADMIN_PASSWORD=$(kubectl exec -ti vault-0 -n vault -- vault kv get -format=json /secrets/postgres-secrets/postgres-creds | jq -r .data.POSTGRES_DMADMIN_PASSWORD)
    echo "ROOT_PASSWORD:$POSTGRES_ROOT_PASSWORD"
    echo "DMADMIN_PASSWORD:$DMADMIN_PASSWORD"
  args:
    executable: /bin/bash      
  register: postgres_passwords
  
- name: Set Base64-encoded passwords as facts
  set_fact:
    postgres_root_password_base64: "{{ (postgres_passwords.stdout_lines | select('match', 'ROOT_PASSWORD:.*') | map('regex_replace', 'ROOT_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"
    dmadmin_password: "{{ (postgres_passwords.stdout_lines | select('match', 'DMADMIN_PASSWORD:.*') | map('regex_replace', 'DMADMIN_PASSWORD:(.*)', '\\1') | list | first) }}"
    dmadmin_password_base64: "{{ (postgres_passwords.stdout_lines | select('match', 'DMADMIN_PASSWORD:.*') | map('regex_replace', 'DMADMIN_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"

- name: postgres-namespace template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/postgres-namespace.j2 dest=$HOME/postgres/postgres-namespace.yaml

- name: postgres-storageclass template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/postgres-storageclass.j2 dest=$HOME/postgres/postgres-storageclass.yaml

- name: postgres-primary-pv template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/postgres-primary-pv.j2 dest=$HOME/postgres/postgres-primary-pv.yaml

- name: postgres config map template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/postgres-configmap.j2 dest=$HOME/postgres/postgres-configmap.yaml

- name: postgres-secret template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/postgres-secret.j2 dest=$HOME/postgres/postgres-secret.yaml

- name: postgres-values template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/postgres-values.j2 dest=$HOME/postgres/postgres-values.yaml

- name: remove previous installation
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    helm delete postgres --namespace "postgres"
    kubectl delete pvc --all --namespace "postgres"
    kubectl delete -f $HOME/postgres/postgres-configmap.yaml
    kubectl delete -f $HOME/postgres/postgres-primary-pv.yaml
    kubectl delete -f $HOME/postgres/postgres-storageclass.yaml
    kubectl delete -f $HOME/postgres/postgres-namespace.yaml
    kubectl delete -f $HOME/postgres/postgres-secret.yaml
  when: postgres_uninstall is defined    
  args:
    chdir: $HOME

- name: setup namespace, persistentvolume for postgres
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl apply -f $HOME/postgres/postgres-namespace.yaml
    kubectl apply -f $HOME/postgres/postgres-storageclass.yaml
    kubectl apply -f $HOME/postgres/postgres-primary-pv.yaml
    kubectl apply -f $HOME/postgres/postgres-configmap.yaml
    kubectl apply -f $HOME/postgres/postgres-secret.yaml
  args:
    chdir: $HOME


- name: Deploy postgres helm chart
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    
    helm upgrade --install postgres oci://registry-1.docker.io/bitnamicharts/postgresql -f $HOME/postgres/postgres-values.yaml --version "{{ postgres_version }}" --namespace "postgres"
    exit 0
  args:
    executable: /bin/bash      
  register: SHELL_STDOUT

- name: debug output
  ansible.builtin.debug: 
    msg: "Helm Install (postgres): stderr: {{ SHELL_STDOUT.stderr_lines }} stdout: {{ SHELL_STDOUT.stdout_lines }}"

- name: wait for pods to come up
  become: yes
  become_user: "{{ vm_username }}"
  shell: kubectl wait --namespace="postgres" --for=condition=Ready pod --all 
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|split('\n')|length == 1
  retries: 6
  delay: 10

- name: debug output
  ansible.builtin.debug: 
    msg: "Get pods (postgres): {{ kubectl_get_pods.stdout | split('\n') }}"

- name: Delete postgres directory
  become: yes
  become_user: "{{ vm_username }}"
  file:
    path: $HOME/postgres
    state: absent