export enum ResponseStatus {
    PENDING = 'PENDING',
    COMPLETED = 'COMPLETED',
    ERROR = 'ERROR'
}

export enum SocketEvents{
    VALIDATE_CONNECTION = 'VALIDATE_CONNECTION',
    VALIDATE_CONNECTION_ACK='VALIDATE_CONNECTION_ACK',
    LIST_PATH='LIST_PATH',
    LIST_PATH_ACK='LIST_PATH_ACK',
    ERROR='ERROR',
    WAKE_UP='WAKE_UP',
    MOUNT_PATH='MOUNT_PATH',
    TASK='TASK',
    TASK_ACK='TASK_ACK',
    TASK_COMPLETED='TASK_COMPLETED',
    TASK_UN_SCANNED = 'TASK_UN_SCANNED',
    STOP_TASK='STOP_TASK'
}


export enum TaskType {
    VALIDATE_CONNECTION = 'VALIDATE_CONNECTION',
    LIST_PATHS='LIST_PATHS',
}

export enum Operations {
    VALIDATE_NFS_CONNECTION='VALIDATE_NFS_CONNECTION',
    VALIDATE_SMB_CONNECTION='VALIDATE_SMB_CONNECTION',
    LIST_NFS_PATHS='LIST_NFS_PATHS',
    LIST_SMB_PATHS='LIST_SMB_PATHS'
}


export enum ScheduleStatus {
    SCHEDULING = 'SCHEDULING',
    SCHEDULED = 'SCHEDULED',
    READY_TO_BE_SCHEDULED = 'READY_TO_BE_SCHEDULED'
}