- name: Ensure destination directories exist
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
    recurse: yes
  loop:
    - { path: "/opt/datamigrator" }
    - { path: "/opt/datamigrator/bin" }
    - { path: "/opt/datamigrator/conf" }
    - { path: "/opt/datamigrator/logs" }
    - { path: "/opt/datamigrator/lock" }
    - { path: "/opt/datamigrator/cronjobs" }

- name: Configure NDM Versions
  become: yes
  copy:
    content: |
      initial_version={{ build_version }}
      current_version={{ build_version }}
      previous_version=N/A
    dest: "/opt/datamigrator/conf/versions.conf"
    owner: root
    group: root

- name: Cleanup service account
  become: yes
  shell: |
    kubectl delete serviceaccount -n datamigrator datamigrator-openbao-sa
  ignore_errors: yes
  when: dm_uninstall is defined

# - name: delete acr pull secert when dm_uninstall is defined
#   become: yes
#   shell: |
#     kubectl delete secret azure-dev-acr-creds --namespace datamigrator
#   ignore_errors: yes
#   when: dm_uninstall is defined and local_cluster is not defined

- name: Create service account and namespace
  become: yes
  shell: |
    kubectl create namespace datamigrator
    kubectl create serviceaccount -n datamigrator datamigrator-openbao-sa

# - name: Create acr pull secert
#   become: yes
#   shell: |
#     kubectl create secret docker-registry azure-dev-acr-creds \
#         --namespace datamigrator \
#         --docker-server={{ acr_registry }} \
#         --docker-username={{ azure_client_id }} \
#         --docker-password={{ azure_client_secret }}
#   ignore_errors: yes
#   when: local_cluster is not defined
