name: Placeholder Checks

on:
  pull_request:
    branches:
      - main
      - 'release/**'
      
permissions: 
  contents: read

jobs:
  dummy-unit-admin-service:
    name: unit-test-cases-and-code-coverage (admin-service)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: |
          echo "Satisfying required check: unit-test-cases-and-code-coverage (admin-service)"

  dummy-unit-config-service:
    name: unit-test-cases-and-code-coverage (config-service)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: |
          echo "Satisfying required check: unit-test-cases-and-code-coverage (config-service)"

  dummy-unit-db-writer:
    name: unit-test-cases-and-code-coverage (db-writer)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: |
          echo "Satisfying required check: unit-test-cases-and-code-coverage (db-writer)"

  dummy-unit-jobs-service:
    name: unit-test-cases-and-code-coverage (jobs-service)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: |
          echo "Satisfying required check: unit-test-cases-and-code-coverage (jobs-service)"

  dummy-unit-reports-service:
    name: unit-test-cases-and-code-coverage (reports-service)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: |
          echo "Satisfying required check: unit-test-cases-and-code-coverage (reports-service)"
  
  dummy-unit-support-service:
    name: unit-test-cases-and-code-coverage (support-service)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: |
          echo "Satisfying required check: unit-test-cases-and-code-coverage (support-service)"

  dummy-unit-worker:
    name: unit-test-cases-and-code-coverage (worker)
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: |
          echo "Satisfying required check: unit-test-cases-and-code-coverage (worker)"