---

- name: create postgres-data directory 
  become: yes
  become_user: "{{ vm_username }}"
  file:
    path: /data/postgres-data
    state: directory
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"   
    mode: 0755