---
- name: Configure openbao data directory
  hosts: default
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-openbao/openbao-data, tags: "openbao-data" }

- name: Install openbao
  hosts: default
  gather_facts: yes
  become: yes
  roles:
    - {
        role: ../roles/configure-openbao/install-openbao,
        tags: "install-openbao",
      }

- name: Setup openbao
  hosts: default
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-openbao/setup-openbao, tags: "setup-openbao" }
