---
- name: Configure data directory for Redis
  hosts: default
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-redis/redis-data, tags: 'redis-data' }

- name: Configure Redis
  hosts: default
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-redis/setup-redis, tags: 'setup-redis' }
