---
- name: Configure data directory for prometheus
  hosts: default
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-prometheus/prometheus-data, tags: 'prometheus-data' }

- name: Configure prometheus
  hosts: default
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-prometheus/setup-prometheus, tags: 'setup-prometheus' }
