---
- name: Deploy datamigrator helm chart
  hosts: default
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/datamigrator/configure-dm, tags: 'configure-dm' }
    - { role: ../roles/datamigrator/helm-chart/install, tags: 'helm-chart-install' }