- name: 6.1. Get current addons state
  become: yes
  command:
    cmd: "{{ microk8s_bin_path }}microk8s.status --format yaml"
  changed_when: no
  register: microk8s_status
  check_mode: no

- name: 6.2. Set current state fact
  set_fact:
    microk8s_status: "{{ microk8s_status.stdout | from_yaml }}"

- name: 6.3. Enable addons
  become: yes
  loop: "{{ microk8s_status.addons }}"
  loop_control:
    label: "{{ item.name }}"
  command:
    cmd: "{{ microk8s_bin_path }}microk8s.enable {{ item.name }}{% if microk8s_plugins[item.name] != True %}:{{ microk8s_plugins[item.name] }}{% endif %}"
  when:
    - item.status == 'disabled'
    - item.name in microk8s_plugins
    - microk8s_plugins[item.name]

- name: 6.3.1. Enable registry for local cluster
  become: yes
  command:
    cmd: "{{ microk8s_bin_path }}microk8s.enable registry"
  when: local_cluster is defined

- name: 6.3.2. Fetch private IP of the server
  set_fact:
    private_ip: "{{ ansible_default_ipv4.address }}"
  when: local_cluster is defined

- name: 6.3.3. Display private_ip
  debug:
    var: private_ip
  when: local_cluster is defined

- name: 6.3.3 Enable metallb load balancer
  become: yes
  command:
    cmd: "{{ microk8s_bin_path }}microk8s.enable metallb:{{ private_ip }}/32"
  when: local_cluster is defined
  
- name: 6.4. Disable addons
  become: yes
  loop: "{{ microk8s_status.addons }}"
  loop_control:
    label: "{{ item.name }}"
  command:
    cmd: "{{ microk8s_bin_path }}microk8s.disable {{ item.name }}"
  when:
    - item.status == 'enabled'
    - item.name in microk8s_plugins
    - not microk8s_plugins[item.name]