export enum USER_PERMISSION_TYPE_ENUM {
  AgentDeployment = "AgentDeployment",
  CreateUser = "CreateUser",
  DeleteProject = "DeleteProject",
  DeleteUser = "DeleteUser",
  InviteUser = "InviteUser",
  ListUsers = "ListUsers",
  ManageConfig = "ManageConfig",
  ManageJob = "ManageJob",
  ManageProject = "ManageProject",
  Reports = "Reports",
  RollbackJob = "RollbackJob",
  UpdateProject = "UpdateProject",
  UpdateUser = "UpdateUser",
  ViewAgentsList = "ViewAgentsList",
  ViewConfig = "ViewConfig",
  ViewJob = "ViewJob",
  ViewLogs = "ViewLogs",
  ViewProject = "ViewProject",
  SpeedTest = "SpeedTest",
  SaveSmtp = "SaveSMTP",
  CreateProject = "CreateProject",
}
