---
# - name: Backup the original ubuntu.sources file
#   copy:
#     src: /etc/apt/sources.list.d/ubuntu.sources
#     dest: /etc/apt/sources.list.d/ubuntu.sources.bak
#     remote_src: yes

# - name: Replace azure.archive.ubuntu.com with archive.ubuntu.com
#   replace:
#     path: /etc/apt/sources.list.d/ubuntu.sources
#     regexp: 'http://azure\.archive\.ubuntu\.com/ubuntu/'
#     replace: 'http://archive.ubuntu.com/ubuntu/'

- name: 2.1. Ensure apt package index is updated
  apt:
    update_cache: yes
    cache_valid_time: 3600
  # retries: 3
  # delay: 10
  # register: update_cache_result
  # until: update_cache_result is succeeded

# - name: Check connectivity to Ubuntu package repository
#   shell: curl -sI http://archive.ubuntu.com | head -n 1
#   register: check_connectivity
#   failed_when: "'200 OK' not in check_connectivity.stdout"

- name: 2.1.1 Upgrade packages which are upgradable
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  when: local_cluster is defined

- name: 2.1.2 Reboot the VM if required
  reboot:
    msg: "Rebooting the VM to apply updates"
  register: reboot_result
  when: local_cluster is defined

- name: 2.1.3 Wait for the VM to come back online
  wait_for_connection:
    delay: 10
    sleep: 5
    timeout: 300
  when: local_cluster is defined

- name: 2.2. Ensure essential packages are installed
  apt:
    name:
      - systemd-timesyncd
      - curl
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - snapd
      - ufw
      - net-tools
      - acl
      - jq
      - xmlstarlet
      - ansible
    state: present
  # retries: 3
  # delay: 10
  # register: install_packages_result
  # until: install_packages_result is succeeded

- name: 2.2.1. Ensure docker is installed on local cluster
  apt:
    name:
      - docker.io
    state: present
  when: local_cluster is defined

- name: 2.2.2. Ensure Docker is started
  service:
    name: docker
    state: started
    enabled: yes
  when: local_cluster is defined

- name: 2.3. Sets the /data directory owner as {{ vm_username }}
  file:
    path: /data
    state: directory
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"
    mode: 0755

- name: 2.4. Sets the /logs directory owner as {{ vm_username }}
  file:
    path: /logs
    state: directory
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"
    mode: 0755

- name: 2.5. Sets default ACL for {{ vm_username }} on /data
  ansible.posix.acl:
    path: /data
    entity: "{{ vm_username }}"
    etype: user
    permissions: rwx
    default: true
    state: present

- name: 2.6. Sets default ACL for {{ vm_username }} on /logs
  ansible.posix.acl:
    path: /logs
    entity: "{{ vm_username }}"
    etype: user
    permissions: rwx
    default: true
    state: present

- name: 2.7. Set the hostname
  command: hostnamectl set-hostname datamigrator

- name: 2.8. Set the system timezone to UTC
  ansible.builtin.command:
    cmd: timedatectl set-timezone UTC
  become: yes

- name: Enable NTP with timedatectl
  become: yes
  command: timedatectl set-ntp true

- name: Set PollIntervalMinSec and PollIntervalMaxSec in timesyncd.conf
  become: yes
  block:
    - lineinfile:
        path: /etc/systemd/timesyncd.conf
        regexp: "^#?PollIntervalMinSec="
        line: "PollIntervalMinSec=20"
        state: present
    - lineinfile:
        path: /etc/systemd/timesyncd.conf
        regexp: "^#?PollIntervalMaxSec="
        line: "PollIntervalMaxSec=600"
        state: present

- name: Restart systemd-timesyncd
  become: yes
  systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: yes
    
# Disable ICMP redirects for security
- name: Disable ICMP redirects
  sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: yes
    sysctl_set: yes
  loop:
    # Disable sending of ICMP redirects
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
    # Disable acceptance of ICMP redirects
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects
    # Disable secure ICMP redirects
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects

- name: Set recommended SSH ciphers
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Ciphers'
    line: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
    state: present
  notify: Restart SSH

- name: Set recommended SSH MACs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MACs'
    line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
    state: present
  notify: Restart SSH
