#!/usr/bin/env node

/**
 * NDM Worker Metrics Query Tool - Direct Pushgateway Access
 * Usage: node simple-test.js <control_plane_ip> <worker_id>
 * Example: node simple-test.js 172.30.203.35 0b02b6ea-7771-4fa3-b42a-7441261c7425
 */

const http = require('http');

// Parse command line arguments
const args = process.argv.slice(2);

function showUsage() {
  console.log(' NDM Worker Metrics Query Tool (Direct Pushgateway Access)');
  console.log('');
  console.log('Usage:');
  console.log('  node simple-test.js <control_plane_ip> <worker_id>');
  console.log('');
  console.log('Example:');
  console.log('  node simple-test.js 172.30.203.35 0b02b6ea-7771-4fa3-b42a-7441261c7425');
  console.log('');
  console.log('Features:');
  console.log('   No SSH required');
  console.log('   No port forwarding needed');
  console.log('   Direct HTTP access to Pushgateway');
  console.log('   Parses Prometheus text format');
  console.log('');
}

// Validate arguments
if (args.length !== 2 || args.includes('--help') || args.includes('-h')) {
  showUsage();
  process.exit(args.includes('--help') || args.includes('-h') ? 0 : 1);
}

const CONTROL_PLANE_IP = args[0];
const WORKER_ID = args[1];
const PUSHGATEWAY_URL = `http://${CONTROL_PLANE_IP}:9091`;

// Function to make HTTP request to Pushgateway
function queryPushgateway(path = '/metrics') {
  return new Promise((resolve, reject) => {
    const url = `${PUSHGATEWAY_URL}${path}`;
    
    http.get(url, (res) => {
      let data = '';
      
      res.on('data', (chunk) => {
        data += chunk;
      });
      
      res.on('end', () => {
        resolve({ statusCode: res.statusCode, data });
      });
    }).on('error', (error) => {
      reject(error);
    });
  });
}

// Parse Prometheus text format and extract worker metrics
function parsePrometheusMetrics(textData, workerId) {
  const lines = textData.split('\n');
  const workerMetrics = {
    memory: {},
    cpu: {},
    disk: {},
    network: {},
    threads: {},
    info: {}
  };
  
  lines.forEach(line => {
    if (line.startsWith('#') || !line.includes(`worker_id="${workerId}"`)) {
      return;
    }
    
    // Parse memory metrics (system memory)
    if (line.includes('worker_system_memory')) {
      const typeMatch = line.match(/type="([^"]+)"/);
      const valueMatch = line.match(/\s+(\d+(?:\.\d+)?(?:e[+-]?\d+)?)$/);
      if (typeMatch && valueMatch) {
        workerMetrics.memory[typeMatch[1]] = parseFloat(valueMatch[1]);
      }
    }
    
    // Parse Node.js heap metrics (auto-generated by collectDefaultMetrics)
    if (line.includes('worker_nodejs_heap_size_used_bytes')) {
      const valueMatch = line.match(/\s+(\d+(?:\.\d+)?(?:e[+-]?\d+)?)$/);
      if (valueMatch) {
        workerMetrics.memory.nodejs_heap_used = parseFloat(valueMatch[1]);
      }
    }
    
    if (line.includes('worker_nodejs_heap_size_total_bytes')) {
      const valueMatch = line.match(/\s+(\d+(?:\.\d+)?(?:e[+-]?\d+)?)$/);
      if (valueMatch) {
        workerMetrics.memory.nodejs_heap_total = parseFloat(valueMatch[1]);
      }
    }
    
    if (line.includes('worker_nodejs_heap_space_size_used_bytes')) {
      const spaceMatch = line.match(/space="([^"]+)"/);
      const valueMatch = line.match(/\s+(\d+(?:\.\d+)?(?:e[+-]?\d+)?)$/);
      if (spaceMatch && valueMatch) {
        workerMetrics.memory[`heap_space_${spaceMatch[1]}_used`] = parseFloat(valueMatch[1]);
      }
    }
    
    // Parse CPU metrics
    if (line.includes('worker_system_cpu_usage')) {
      const coreMatch = line.match(/core="([^"]+)"/);
      const valueMatch = line.match(/\s+(\d+(?:\.\d+)?(?:e[+-]?\d+)?)$/);
      if (coreMatch && valueMatch) {
        workerMetrics.cpu[coreMatch[1]] = parseFloat(valueMatch[1]);
      }
    }
    
    // Parse worker info
    if (line.includes('worker_info')) {
      const versionMatch = line.match(/label_build_version="([^"]+)"/);
      const platformMatch = line.match(/platform="([^"]+)"/);
      if (versionMatch) workerMetrics.info.version = versionMatch[1];
      if (platformMatch) workerMetrics.info.platform = platformMatch[1];
    }
    
    // Parse thread metrics
    if (line.includes('worker_threads_status')) {
      const statusMatch = line.match(/status="([^"]+)"/);
      const valueMatch = line.match(/\s+(\d+(?:\.\d+)?(?:e[+-]?\d+)?)$/);
      if (statusMatch && valueMatch) {
        workerMetrics.threads[statusMatch[1]] = parseInt(valueMatch[1]);
      }
    }
    
    // Parse active tasks
    if (line.includes('worker_tasks_active_total')) {
      const valueMatch = line.match(/\s+(\d+(?:\.\d+)?(?:e[+-]?\d+)?)$/);
      if (valueMatch) {
        workerMetrics.threads.activeTasks = parseInt(valueMatch[1]);
      }
    }
  });
  
  return workerMetrics;
}

// Format bytes helper
function formatBytes(bytes) {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

// Main function
async function queryWorkerMetrics() {
  console.log(' NDM Worker Metrics Query Tool');
  console.log('=====================================');
  console.log(` Control Plane: ${CONTROL_PLANE_IP}`);
  console.log(` Worker ID: ${WORKER_ID}`);
  console.log(` Pushgateway URL: ${PUSHGATEWAY_URL}`);
  console.log(` Query Time: ${new Date().toISOString()}`);
  console.log('');
  
  try {
    // Test Pushgateway connectivity
    console.log('🔗 Testing Pushgateway connectivity...');
    const response = await queryPushgateway('/metrics');
    
    if (response.statusCode !== 200) {
      throw new Error(`Pushgateway returned status ${response.statusCode}`);
    }
    
    console.log(' Pushgateway accessible');
    console.log(` Response size: ${response.data.length} bytes`);
    console.log('');
    
    // Parse metrics for specific worker
    console.log('  Parsing worker metrics...');
    const workerMetrics = parsePrometheusMetrics(response.data, WORKER_ID);
    
    // Display results
    console.log(' WORKER METRICS SUMMARY');
    console.log('=========================');
    
    // Worker Info
    if (Object.keys(workerMetrics.info).length > 0) {
      console.log('ℹ  Worker Information:');
      if (workerMetrics.info.version) {
        console.log(`    Version: ${workerMetrics.info.version}`);
      }
      if (workerMetrics.info.platform) {
        console.log(`    Platform: ${workerMetrics.info.platform}`);
      }
      console.log('');
    }
    
    // Memory Metrics
    if (Object.keys(workerMetrics.memory).length > 0) {
      console.log(' Memory Usage:');
      
      // System Memory (from worker_system_memory)
      if (workerMetrics.memory.total) {
        console.log(`    System Total: ${formatBytes(workerMetrics.memory.total)}`);
      }
      if (workerMetrics.memory.used) {
        console.log(`    System Used: ${formatBytes(workerMetrics.memory.used)}`);
      }
      if (workerMetrics.memory.free) {
        console.log(`    System Free: ${formatBytes(workerMetrics.memory.free)}`);
      }
      if (workerMetrics.memory.usage_percent) {
        console.log(`    System Usage: ${workerMetrics.memory.usage_percent.toFixed(2)}%`);
        
        // Highlight high memory usage
        if (workerMetrics.memory.usage_percent > 80) {
          console.log('     HIGH SYSTEM MEMORY USAGE!');
        }
      }
      
      // Node.js Heap Memory (from collectDefaultMetrics)
      if (workerMetrics.memory.nodejs_heap_used) {
        console.log(`    Node.js Heap Used: ${formatBytes(workerMetrics.memory.nodejs_heap_used)}`);
      }
      if (workerMetrics.memory.nodejs_heap_total) {
        console.log(`    Node.js Heap Total: ${formatBytes(workerMetrics.memory.nodejs_heap_total)}`);
        
        // Calculate heap usage percentage
        if (workerMetrics.memory.nodejs_heap_used && workerMetrics.memory.nodejs_heap_total) {
          const heapUsagePercent = (workerMetrics.memory.nodejs_heap_used / workerMetrics.memory.nodejs_heap_total) * 100;
          console.log(`    Node.js Heap Usage: ${heapUsagePercent.toFixed(2)}%`);
          
          if (heapUsagePercent > 90) {
            console.log('     HIGH NODE.JS HEAP USAGE!');
          }
        }
      }
      
      console.log('');
    }
    
    // CPU Metrics
    if (Object.keys(workerMetrics.cpu).length > 0) {
      console.log(' CPU Usage:');
      if (workerMetrics.cpu.average !== undefined) {
        console.log(`    Average: ${workerMetrics.cpu.average.toFixed(2)}%`);
      }
      
      // Show individual cores (limit to first 4)
      const cores = Object.keys(workerMetrics.cpu).filter(key => key.startsWith('cpu')).slice(0, 4);
      cores.forEach(core => {
        console.log(`    ${core}: ${workerMetrics.cpu[core].toFixed(2)}%`);
      });
      
      if (cores.length < Object.keys(workerMetrics.cpu).filter(k => k.startsWith('cpu')).length) {
        console.log(`   ... and ${Object.keys(workerMetrics.cpu).filter(k => k.startsWith('cpu')).length - cores.length} more cores`);
      }
      console.log('');
    }
    
    // Thread Metrics
    if (Object.keys(workerMetrics.threads).length > 0) {
      console.log(' Worker Threads:');
      if (workerMetrics.threads.total !== undefined) {
        console.log(`    Total Threads: ${workerMetrics.threads.total}`);
      }
      if (workerMetrics.threads.available !== undefined) {
        console.log(`    Available: ${workerMetrics.threads.available}`);
      }
      if (workerMetrics.threads.busy !== undefined) {
        console.log(`    Busy: ${workerMetrics.threads.busy}`);
      }
      if (workerMetrics.threads.activeTasks !== undefined) {
        console.log(`    Active Tasks: ${workerMetrics.threads.activeTasks}`);
      }
      console.log('');
    }
    
    // Check if no metrics found
    const hasAnyMetrics = Object.values(workerMetrics).some(category => 
      Object.keys(category).length > 0
    );
    
    if (!hasAnyMetrics) {
      console.log('  No metrics found for this worker ID');
      console.log('');
      console.log('Possible reasons:');
      console.log('   • Worker ID is incorrect');
      console.log('   • Worker is not running or has not pushed metrics yet');
      console.log('   • Metrics collection is disabled on the worker');
      console.log('   • Worker has not completed its first metrics push cycle');
      console.log('');
      console.log(' Try running a migration job to generate metrics activity');
    } else {
      console.log(' Metrics query completed successfully!');
    }
    
  } catch (error) {
    console.error(' Failed to query worker metrics:', error.message);
    console.log('');
    console.log('Troubleshooting:');
    console.log('   • Verify control plane IP is correct');
    console.log('   • Check if Pushgateway is running on port 9091');
    console.log('   • Ensure worker is connected and pushing metrics');
    console.log('   • Try: curl http://' + CONTROL_PLANE_IP + ':9091/metrics');
    process.exit(1);
  }
}

// Validate input and run
const ipRegex = /^(\d{1,3}\.){3}\d{1,3}$/;
const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

if (!ipRegex.test(CONTROL_PLANE_IP)) {
  console.error(' Invalid IP address format:', CONTROL_PLANE_IP);
  process.exit(1);
}

if (!uuidRegex.test(WORKER_ID)) {
  console.error(' Invalid worker ID format (expected UUID):', WORKER_ID);
  process.exit(1);
}

queryWorkerMetrics();
