- name: Testing retries
  fail:
    msg: "This is an intentional failure to test packer build retries"

- name: Configure user access on VM
  import_playbook: configure-user.yaml

- name: Configure VM by upgrading packages
  import_playbook: configure-vm.yaml

- name: Configure cloud init
  import_playbook: configure-cloud-init.yaml
  when: local_cluster is not defined

- name: Configure Worker
  import_playbook: configure-worker.yaml

- name: Configure Fluentd Logging
  import_playbook: install-fluentd.yaml

- name: Configure OVF customization for vSphere
  import_playbook: configure-ovf.yaml
  when: 
    - vsphere_build | default(false)
    - local_cluster is not defined
