---

- name: delete grafana-data directory if uninstall flag is defined 
  become: yes
  file:
    path: /data/grafana-data
    state: absent
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"   
    mode: 0755
  when: grafana_uninstall is defined

- name: delete loki-data directory if uninstall flag is defined 
  become: yes
  file:
    path: /data/loki-data
    state: absent
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"   
    mode: 0755
  when: grafana_uninstall is defined

- name: create grafana-data directory 
  become: yes
  file:
    path: /data/grafana-data
    state: directory
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"   
    mode: 0755

- name: create loki-data directory 
  become: yes
  file:
    path: /data/loki-data
    state: directory
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"   
    mode: 0755