---
- name: Configure data directory for Postgres
  hosts: servers
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-postgres/postgres-data, tags: 'postgres-data' }

- name: Configure Postgres
  hosts: servers
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-postgres/setup-postgres, tags: 'setup-postgres' }
