---
- name: Configure data directory for rabbitmq
  hosts: servers
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-rabbitmq/rabbitmq-data, tags: 'rabbitmq-data' }

- name: Configure rabbitmq
  hosts: servers
  gather_facts: yes
  become: yes
  roles:
    - { role: ../roles/configure-rabbitmq/setup-rabbitmq, tags: 'setup-rabbitmq' }
