appName: "support-service"
kubeApiVersion: "apps/v1"
replicaCount: 1

image:
  repository: ndm-support-service

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/role: "datamigrator-role"
  vault.hashicorp.com/agent-inject-secret-postgres.env: "secrets/postgres-secrets/postgres-creds"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-template-postgres.env: |
    {{- with secret "secrets/postgres-secrets/postgres-creds" -}}
    export DB_USER="{{ .Data.POSTGRES_DMADMIN_USER }}"
    export DB_PASSWORD="{{ .Data.POSTGRES_DMADMIN_PASSWORD }}"
    {{- end }}

serviceAccountName: datamigrator-openbao-sa

args:
  - "--source-vault"

imagePullSecrets: azure-dev-acr-creds

env:
  - name: MY_HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

  - name: DB_PORT
    value: "5432"
  - name: DB_HOST
    value: "postgresql.postgres.svc.cluster.local"
  - name: DB_NAME
    value: "datamigrator"
  - name: SCHEMA
    value: "datamigrator"

  - name: TEMPORAL_ADDRESS
    value: "temporaltest-frontend.temporal.svc.cluster.local:7233"

  - name: BASE_LOG_PATH
    value: "/ndm-logs"

  - name: OUTPUT_ZIP_PATH
    value: "/generated-zips"

  - name: CONFIG_BASE_URL
    value: "http://config-service-service:3000/api/v1"

  - name: PROMETHEUS_BASE_URL
    value: "http://prometheus-server.prometheus.svc.cluster.local:80/api/v1"

  - name: PROMETHEUS_TIMEOUT
    value: "5m"

  - name: STEP_1Hr
    value: "1h"

  - name: STEP_4Hr
    value: "4h"

  - name: STEP_5MIN
    value: "5m"

  - name: NODE_DISK_THRESHOLD
    value: "90"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

persistentVolumes:
  - name: ndm-logs
    mountPath: /ndm-logs
    hostPath: /ndm-logs
  - name: generated-zips
    mountPath: /generated-zips
    hostPath: /generated-zips
