{
 "title": "Temporal Core SDK (OTel) Metrics",
 "description": "Temporal SDKs \n",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Workflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Workflow Completion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_workflow_completed_total{exported_job=\"temporal-core-sdk\"}\n",
     "legendFormat": "WorkflowType {{workflow_type}}"
    }
   ]
  },
  {
   "title": "Workflow End-To-End Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_workflow_endtoend_latency_seconds_sum{exported_job=\"temporal-core-sdk\"}\n",
     "legendFormat": "WorkflowType {{workflow_type}}"
    }
   ]
  },
  { "title": "Workflow Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Workflow Task Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_workflow_task_queue_poll_succeed_total{exported_job=\"temporal-core-sdk\"}\n",
     "legendFormat": "task_queue:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Workflow Task Schedule To Start (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_workflow_task_schedule_to_start_latency_seconds_sum{exported_job=\"temporal-core-sdk\"}\n",
     "legendFormat": "task_queue:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Workflow Task Execution Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_workflow_task_execution_latency_seconds_sum{exported_job=\"temporal-core-sdk\"}\n",
     "legendFormat": "workflow_type:{{workflow_type}}"
    }
   ]
  },
  {
   "title": "Workflow Task Replay Latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_workflow_task_replay_latency_seconds_count{exported_job=\"temporal-core-sdk\"}\n",
     "legendFormat": "workflow_type:{{workflow_type}}"
    }
   ]
  },
  {
   "title": "Workflow Task Empty Polls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_workflow_task_queue_poll_empty_total{exported_job=\"temporal-core-sdk\"}\n",
     "legendFormat": "task_queue:{{task_queue}}"
    }
   ]
  },
  { "title": "Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Activity Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (activity_type) (temporal_sdk_metrics_activity_schedule_to_start_latency_seconds_bucket{exported_job=\"temporal-core-sdk\"})",
     "legendFormat": "{{activity_type}}"
    }
   ]
  },
  {
   "title": "Activity Execution Latencies (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (activity_type) (temporal_sdk_metrics_activity_execution_latency_seconds_bucket{exported_job=\"temporal-core-sdk\"})",
     "legendFormat": "{{activity_type}}"
    }
   ]
  },
  { "title": "Activity Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Empty Activity Polls ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_activity_poll_no_task_total{exported_job=\"temporal-core-sdk\"}",
     "legendFormat": "task_queue:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Activity Schedule To Start (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (activity_type) (temporal_sdk_metrics_activity_schedule_to_start_latency_seconds_bucket{exported_job=\"temporal-core-sdk\"})",
     "legendFormat": "{{activity_type}}"
    }
   ]
  },
  { "title": "Slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Slots Available",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_worker_task_slots_available{exported_job=\"temporal-core-sdk\"}",
     "legendFormat": "worker_type:{{worker_type}}"
    }
   ]
  },
  {
   "title": "Slots Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "temporal_sdk_metrics_worker_task_slots_used{exported_job=\"temporal-core-sdk\"}",
     "legendFormat": "worker_type:{{worker_type}}"
    }
   ]
  }
 ]
}