---
- name: 1.1. Set up sudo for 'ubuntu' (with passwordless access)
  become: yes
  copy:
    dest: "/etc/sudoers.d/ubuntu"
    content: |
      ubuntu ALL=(ALL) NOPASSWD: ALL
    mode: "0440"

# - name: 1.2. Create the '{{ vm_username }}' user with a home directory
#   become: yes
#   user:
#     name: "{{ vm_username }}"
#     state: present
#     home: "/home/{{ vm_username }}"
#     shell: /bin/bash
#     groups: sudo
#     append: yes

- name: 1.2. Create the {{ vm_username }} user account
  user: name={{ vm_username }} state=present home=/home/{{ vm_username }} createhome=yes shell=/bin/bash

- name: 1.3. Set up sudo for '{{ vm_username }}' (with passwordless access)
  become: yes
  copy:
    dest: "/etc/sudoers.d/{{ vm_username }}"
    content: |
      {{ vm_username }} ALL=(ALL) NOPASSWD: ALL
    mode: "0440"

- name: 1.4. Disable root SSH access
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present

- name: 1.5. Deny SSH access for '{{ vm_username }}' (datamigrate user)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?DenyUsers'
    line: 'DenyUsers {{ vm_username }}'
    state: present

- name: 1.6. Allow SSH access only for the 'ubuntu' user
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AllowUsers'
    line: 'AllowUsers ubuntu'
    state: present

- name: 1.7. Disable password authentication for SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

- name: 1.8. Validate sudoers file for '{{ vm_username }}'
  become: yes
  command: visudo -cf /etc/sudoers.d/{{ vm_username }}
  register: visudo_check
  failed_when: visudo_check.rc != 0
  changed_when: false

- name: 1.9. Confirm the new user can log in (only for testing the user creation)
  become: yes
  shell: "su - '{{ vm_username }}' -c 'whoami'"
  register: login_check
  changed_when: false

- name: 1.10. Debug the login check
  become: yes
  debug:
    var: login_check.stdout
