
- name: Copy Docker image tar files to target
  copy:
    src: "../../../artifacts/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0644'
  with_items:
    - ndm-docker-images.tar
    - ndm-admin-entry-alpine.tar
    - ndm-fluentd-loki-v1.17-1.tar
  when: local_cluster is not defined

- name: Side-load images to microk8s
  command: microk8s images import /tmp/{{ item }}
  register: microk8s_import_result
  with_items:
    - ndm-docker-images.tar
    - ndm-admin-entry-alpine.tar
    - ndm-fluentd-loki-v1.17-1.tar
  when: local_cluster is not defined

- name: Display microk8s import result
  debug:
    var: microk8s_import_result.results
  when: local_cluster is not defined

- name: Remove tar files from target
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - ndm-docker-images.tar
    - ndm-admin-entry-alpine.tar
    - ndm-fluentd-loki-v1.17-1.tar
  when: local_cluster is not defined