- name: Copy Docker image tar file to target
  copy:
    src: "../../../artifacts/ndm-docker-images.tar"
    dest: "{{ ansible_env.HOME }}/ndm-docker-images.tar"
    mode: '0644'
  when: local_cluster is not defined

- name: Import third-party Docker images into MicroK8s containerd
  become: yes
  command: "microk8s ctr image import {{ ansible_env.HOME }}/ndm-docker-images.tar"
  when: local_cluster is not defined

- name: Compress third-party Docker image tar to reduce VM image size
  command: "gzip -1 {{ ansible_env.HOME }}/ndm-docker-images.tar"
  args:
    removes: "{{ ansible_env.HOME }}/ndm-docker-images.tar"
  when: local_cluster is not defined
