ALTER TABLE worker
  ADD COLUMN IF NOT EXISTS upgrade_bundle_staged VARCHAR(20) DEFAULT 'IDLE',
  ADD COLUMN IF NOT EXISTS worker_version VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS staged_version VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS upgrade_execution_status VARCHAR(20) DEFAULT 'IDLE', 
  ADD COLUMN IF NOT EXISTS upgrade_completed_at TIMESTAMP DEFAULT NULL;

ALTER TABLE upgrade_bundles
  ADD COLUMN IF NOT EXISTS multicast_workflow_id VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS execution_workflow_id VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS upgrade_worker_triggered_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS worker_upload_status VARCHAR(20) DEFAULT 'IDLE',
  ADD COLUMN IF NOT EXISTS worker_upgrade_status VARCHAR(20) DEFAULT 'IDLE';
