ALTER TABLE worker
  ADD COLUMN IF NOT EXISTS upgrade_bundle_staged VARCHAR(20) DEFAULT 'IDLE',
  ADD COLUMN IF NOT EXISTS worker_version VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS staged_version VARCHAR(100) DEFAULT NULL;
