-- Rewrite storage_jobs_overview_mv to use job_stats_summary_mv instead of LATERAL inventory scans
-- This eliminates expensive full-partition scans of the inventory table (60M+ rows) on each refresh,
-- replacing them with a simple JOIN to the pre-aggregated job_stats_summary_mv (one row per job_run).
DROP MATERIALIZED VIEW IF EXISTS storage_jobs_overview_mv;

CREATE MATERIALIZED VIEW storage_jobs_overview_mv AS
WITH ALL_DISCOVERY_RUNS AS (
    SELECT
        DISTINCT
        P.ID AS PROJECT_ID,
        P.PROJECT_NAME AS PROJECT_NAME,
        C.ID AS CONFIG_ID,
        JC.ID AS JOB_CONFIG_ID,
        JR.ID AS JOB_RUN_ID,
        JR.STATUS AS JOB_RUN_STATUS,
        JR.CREATED_AT AS JOB_RUN_CREATED_AT,
        'DISCOVER' AS JOB_TYPE,
        ROW_NUMBER() OVER (
            PARTITION BY JC.ID
            ORDER BY JR.CREATED_AT DESC
        ) AS RN
    FROM PROJECT P
    LEFT JOIN CONFIG C ON P.ID = C.PROJECT_ID
    LEFT JOIN FILE_SERVER FS ON C.ID = FS.CONFIG_ID
    LEFT JOIN VOLUME V ON FS.ID = V.FILE_SERVER_ID
    LEFT JOIN JOBCONFIG JC ON V.ID = JC.SOURCE_PATH_ID
    LEFT JOIN JOBRUN JR ON JC.ID = JR.JOB_CONFIG_ID
    WHERE JC.JOB_TYPE = 'DISCOVER'
      AND JR.ID IS NOT NULL
),
ALL_MIGRATE_RUNS AS (
    SELECT
        DISTINCT
        P.ID AS PROJECT_ID,
        P.PROJECT_NAME AS PROJECT_NAME,
        C.ID AS CONFIG_ID,
        JC.ID AS JOB_CONFIG_ID,
        JR.ID AS JOB_RUN_ID,
        JR.STATUS AS JOB_RUN_STATUS,
        JR.CREATED_AT AS JOB_RUN_CREATED_AT,
        'MIGRATE' AS JOB_TYPE,
        1 AS RN
    FROM PROJECT P
    LEFT JOIN CONFIG C ON P.ID = C.PROJECT_ID
    LEFT JOIN FILE_SERVER FS ON C.ID = FS.CONFIG_ID
    LEFT JOIN VOLUME V ON FS.ID = V.FILE_SERVER_ID
    LEFT JOIN JOBCONFIG JC ON V.ID = JC.SOURCE_PATH_ID
    LEFT JOIN JOBRUN JR ON JC.ID = JR.JOB_CONFIG_ID
    WHERE JC.JOB_TYPE = 'MIGRATE'
      AND JR.ID IS NOT NULL
),
ALL_CUTOVER_RUNS AS (
    SELECT
        DISTINCT
        P.ID AS PROJECT_ID,
        P.PROJECT_NAME AS PROJECT_NAME,
        C.ID AS CONFIG_ID,
        JC.ID AS JOB_CONFIG_ID,
        JR.ID AS JOB_RUN_ID,
        JR.STATUS AS JOB_RUN_STATUS,
        JR.CREATED_AT AS JOB_RUN_CREATED_AT,
        'CUT_OVER' AS JOB_TYPE,
        1 AS RN
    FROM PROJECT P
    LEFT JOIN CONFIG C ON P.ID = C.PROJECT_ID
    LEFT JOIN FILE_SERVER FS ON C.ID = FS.CONFIG_ID
    LEFT JOIN VOLUME V ON FS.ID = V.FILE_SERVER_ID
    LEFT JOIN JOBCONFIG JC ON V.ID = JC.SOURCE_PATH_ID
    LEFT JOIN JOBRUN JR ON JC.ID = JR.JOB_CONFIG_ID
    WHERE JC.JOB_TYPE = 'CUT_OVER'
      AND JR.ID IS NOT NULL
),
LATEST_DISCOVERY_RUNS AS (
    SELECT * FROM ALL_DISCOVERY_RUNS WHERE RN = 1
),
COMPLETED_DISCOVERY_RUNS AS (
    SELECT * FROM LATEST_DISCOVERY_RUNS WHERE JOB_RUN_STATUS = 'COMPLETED'
),
DISCOVERY_SIZE_JOB_RUNS AS (
    SELECT PROJECT_ID, CONFIG_ID, JOB_RUN_ID, 'MIGRATE' AS SOURCE_TYPE
    FROM ALL_MIGRATE_RUNS
    UNION ALL
    SELECT PROJECT_ID, CONFIG_ID, JOB_RUN_ID, 'CUT_OVER' AS SOURCE_TYPE
    FROM ALL_CUTOVER_RUNS
    UNION ALL
    SELECT PROJECT_ID, CONFIG_ID, JOB_RUN_ID, 'COMPLETED_DISCOVERY' AS SOURCE_TYPE
    FROM COMPLETED_DISCOVERY_RUNS
),
MIGRATION_SIZE_JOB_RUNS AS (
    SELECT PROJECT_ID, CONFIG_ID, JOB_RUN_ID, 'MIGRATE' AS SOURCE_TYPE
    FROM ALL_MIGRATE_RUNS
    UNION ALL
    SELECT PROJECT_ID, CONFIG_ID, JOB_RUN_ID, 'CUT_OVER' AS SOURCE_TYPE
    FROM ALL_CUTOVER_RUNS
),
DISCOVERY_SIZE_CALCULATION AS (
    SELECT
        DSJR.PROJECT_ID,
        DSJR.CONFIG_ID,
        COALESCE(SUM(JSM.total_size), 0) AS TOTAL_DISCOVERED_SIZE,
        COUNT(DISTINCT DSJR.JOB_RUN_ID) AS DISCOVERY_JOB_RUN_COUNT
    FROM DISCOVERY_SIZE_JOB_RUNS DSJR
    LEFT JOIN job_stats_summary_mv JSM ON DSJR.JOB_RUN_ID = JSM.job_run_id
    GROUP BY DSJR.PROJECT_ID, DSJR.CONFIG_ID
),
MIGRATION_SIZE_CALCULATION AS (
    SELECT
        MSJR.PROJECT_ID,
        MSJR.CONFIG_ID,
        COALESCE(SUM(JSM.total_size), 0) AS TOTAL_MIGRATED_SIZE,
        COUNT(DISTINCT MSJR.JOB_RUN_ID) AS MIGRATION_JOB_RUN_COUNT
    FROM MIGRATION_SIZE_JOB_RUNS MSJR
    LEFT JOIN job_stats_summary_mv JSM ON MSJR.JOB_RUN_ID = JSM.job_run_id
    GROUP BY MSJR.PROJECT_ID, MSJR.CONFIG_ID
)
SELECT
    COALESCE(DSC.PROJECT_ID, MSC.PROJECT_ID) AS PROJECT_ID,
    COALESCE(DSC.CONFIG_ID, MSC.CONFIG_ID) AS CONFIG_ID,
    COALESCE(DSC.TOTAL_DISCOVERED_SIZE, 0) AS TOTAL_DISCOVERED_SIZE,
    COALESCE(MSC.TOTAL_MIGRATED_SIZE, 0) AS TOTAL_MIGRATED_SIZE,
    COALESCE(DSC.TOTAL_DISCOVERED_SIZE, 0) - COALESCE(MSC.TOTAL_MIGRATED_SIZE, 0) AS TOTAL_PENDING_SIZE,
    COALESCE(DSC.DISCOVERY_JOB_RUN_COUNT, 0) AS DEBUG_DISCOVERY_JOB_RUNS,
    COALESCE(MSC.MIGRATION_JOB_RUN_COUNT, 0) AS DEBUG_MIGRATION_JOB_RUNS,
    NOW() AS LAST_REFRESHED
FROM DISCOVERY_SIZE_CALCULATION DSC
FULL OUTER JOIN MIGRATION_SIZE_CALCULATION MSC
    ON DSC.PROJECT_ID = MSC.PROJECT_ID
    AND DSC.CONFIG_ID = MSC.CONFIG_ID;

CREATE INDEX IF NOT EXISTS idx_storage_jobs_overview_mv_project_config
ON storage_jobs_overview_mv (project_id, config_id);

CREATE INDEX IF NOT EXISTS idx_storage_jobs_overview_mv_project_id
ON storage_jobs_overview_mv (project_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_storage_jobs_overview_mv_config_id
ON storage_jobs_overview_mv (config_id);
