ALTER TABLE jobconfig ADD COLUMN IF NOT EXISTS preserve_permissions BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE job_options ADD COLUMN IF NOT EXISTS preserve_permissions BOOLEAN DEFAULT TRUE NOT NULL;
