---
- name: Creates redis directory
  become: yes
  become_user: "{{ vm_username }}"
  file:
    path: $HOME/redis
    state: directory

- name: generate random password for redis
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    export REDIS_PASSWORD=$(kubectl exec -ti vault-0 -n vault -- vault kv get -format=json /secrets/redis-secrets/redis-creds | jq -r .data.REDIS_PASSWORD)
    echo "REDIS_PASSWORD:$REDIS_PASSWORD"
  args:
    executable: /bin/bash      
  register: redis_password

- name: Set Base64-encoded password as fact
  set_fact:
    redis_password: "{{ (redis_password.stdout_lines | select('match', 'REDIS_PASSWORD:.*') | map('regex_replace', 'REDIS_PASSWORD:(.*)', '\\1') | list | first) }}"
    redis_password_base64: "{{ (redis_password.stdout_lines | select('match', 'REDIS_PASSWORD:.*') | map('regex_replace', 'REDIS_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"

- name: redis-namespace template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/redis-namespace.j2 dest=$HOME/redis/redis-namespace.yaml

- name: redis configmap template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/redis-configmap.j2 dest=$HOME/redis/redis-configmap.yaml

- name: redis-pv template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/redis-pv.j2 dest=$HOME/redis/redis-pv.yaml

- name: redis-storageclass template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/redis-storageclass.j2 dest=$HOME/redis/redis-storageclass.yaml

- name: redis-secret template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/redis-secret.j2 dest=$HOME/redis/redis-secret.yaml

- name: redis-values template
  become: yes
  become_user: "{{ vm_username }}"
  template: src=./templates/redis-values.j2 dest=$HOME/redis/redis-values.yaml

- name: Cleanup service account
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl delete serviceaccount -n redis redis-sa
  when: redis_uninstall is defined
  
- name: remove previous redis installation
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    helm delete redis --namespace "redis"
    kubectl delete pvc --all --namespace "redis"
    kubectl delete -f $HOME/redis/redis-configmap.yaml
    kubectl delete -f $HOME/redis/redis-pv.yaml
    kubectl delete -f $HOME/redis/redis-storageclass.yaml
    kubectl delete -f $HOME/redis/redis-secret.yaml
    kubectl delete -f $HOME/redis/redis-namespace.yaml
  when: redis_uninstall is defined    
  args:
    chdir: $HOME

- name: setup namespace, persistentvolume for redis
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl apply -f $HOME/redis/redis-namespace.yaml
    kubectl apply -f $HOME/redis/redis-storageclass.yaml
    kubectl apply -f $HOME/redis/redis-pv.yaml
    kubectl apply -f $HOME/redis/redis-configmap.yaml  
    kubectl apply -f $HOME/redis/redis-secret.yaml
  args:
    chdir: $HOME

- name: Create service account
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    kubectl create serviceaccount -n redis redis-sa

- name: Deploy redis helm chart
  become: yes
  become_user: "{{ vm_username }}"
  shell: |
    helm upgrade --install redis oci://registry-1.docker.io/bitnamicharts/redis -f $HOME/redis/redis-values.yaml --namespace "redis" --version "{{ redis_version }}"
    exit 0
  args:
    executable: /bin/bash      
  register: SHELL_STDOUT

- name: debug output
  ansible.builtin.debug: 
    msg: "Helm Install (redis): stderr: {{ SHELL_STDOUT.stderr_lines }} stdout: {{ SHELL_STDOUT.stdout_lines }}"

- name: Wait for 20 seconds before waiting for pods to come up
  ansible.builtin.pause:
    seconds: 20



- name: Wait for pods to come up and handle failure
  block:
    - name: Wait for pods to come up
      become: yes
      become_user: "{{ vm_username }}"
      shell: |
        kubectl wait --namespace="redis" --for=condition=Ready pod --all
      register: kubectl_get_pods
      retries: 5
      delay: 25
      until: kubectl_get_pods.rc == 0

    - name: debug output
      ansible.builtin.debug: 
        msg: "Get pods (redis): {{ kubectl_get_pods.stdout | split('\n') }}"

    - name: Check redis pod status
      shell: kubectl get pods -n redis
      register: pod_status

    - debug:
        var: pod_status.stdout
  rescue:
    - name: Fetch and display pod logs
      become: yes
      become_user: "{{ vm_username }}"
      shell: |
        for pod in $(kubectl get pods -n redis -o jsonpath='{.items[*].metadata.name}'); do
          echo "Logs for pod: $pod"
          kubectl logs -n redis --tail=20 $pod
          echo "----------------------------------------"
        done
      register: pod_logs
    - name: Display pod logs
      ansible.builtin.debug:
        msg: "{{ pod_logs.stdout }}"
    - name: Fail the play due to pod readiness failure
      fail:
        msg: "Pods did not become ready within the expected time frame."

- name: Delete redis directory
  become: yes
  become_user: "{{ vm_username }}"
  file:
    state: absent
    path: $HOME/redis