---
# Binary file paths
vm_username: datamigrator
vm_uid: 1030
vm_gid: 1030
local_binary_path: /Users/anuragdoshi/Downloads/pkg-5/worker-linux-x64
remote_binary_path: /opt/datamigrator/binary/dm-worker-linux-x64-v1.0.0
