import { ReportValueType } from "./enums";
export const PDFReportHeaders = {
  DISCOVER: [
    "File Server Info",
    "Number of Files",
    "Modified",
    "Created",
    "Access Time",
    "Depth",
    "Space Used",
    "File System Stats",
    "Top 5 File Extensions (with file Capacity and Count)",
    "Maximum Values",
    "Job Run Stats",
    "Biggest",
  ],
};
export enum formatStringTypeCategories {
  Top_File_Extension = "Top 5 File Extensions (with file Capacity and Count)",
}
export const ReportSubCategoriesHeader = {
  "Number of Files": [
    "File Count with File Size: 0B",
    "File Count with File Size: <8KiB",
    "File Count with File Size: 8-64KiB",
    "File Count with File Size: 64KiB-1MiB",
    "File Count with File Size: 1-10MiB",
    "File Count with File Size: 10-100MiB",
    "File Size: 100 MiB - 1 GiB",
    "File Size: 1+ GiB",
  ],
  "Space Used": [
    "Capacity with File Size: 0B",
    "Capacity with File Size: <8KiB",
    "Capacity with File Size: 8-64KiB",
    "Capacity with File Size: 64KiB-1MiB",
    "Capacity with File Size: 1-10MiB",
    "Capacity with File Size: 10-100MiB",
    "Capacity with File Size: 100 MiB - 1 GiB",
    "Capacity with File Size: 1+ GiB",
  ],
  Depth: [
    "Files and Directory with depth: 0-5",
    "Files and Directory with depth: 6-10",
    "Files and Directory with depth: 11-15",
    "Files and Directory with depth: 16-20",
    "Files and Directory with depth: 21-100",
    "Files and Directory with depth: >100",
  ],
  Modified: [
    "File Count with Modification Time 0-1 wk",
    "Capacity with Modification Time 0-1 wk",
    "File Count with Modification Time 1 wk - 1 mo",
    "Capacity with Modification Time 1 wk - 1 mo",
    "File Count with Modification Time 1-3 mo",
    "Capacity with Modification Time 1-3 mo",
    "File Count with Modification Time 3-6 mo",
    "Capacity with Modification Time 3-6 mo",
    "File Count with Modification Time 6-12 mo",
    "Capacity with Modification Time 6-12 mo",
    "File Count with Modification Time 1-2 yr",
    "Capacity with Modification Time 1-2 yr",
    "File Count with Modification Time 2-3 yr",
    "Capacity with Modification Time 2-3 yr",
    "File Count with Modification Time 3-4 yr",
    "Capacity with Modification Time 3-4 yr",
    "File Count with Modification Time 4-5 yr",
    "Capacity with Modification Time 4-5 yr",
    "File Count with Modification Time 5-6 yr",
    "Capacity with Modification Time 5-6 yr",
    "File Count with Modification Time 6-7 yr",
    "Capacity with Modification Time 6-7 yr",
    "File Count with Modification Time 7-8 yr",
    "Capacity with Modification Time 7-8 yr",
    "File Count with Modification Time 8-9 yr",
    "Capacity with Modification Time 8-9 yr",
    "File Count with Modification Time 9-10 yr",
    "Capacity with Modification Time 9-10 yr",
    "File Count with Modification Time 10+ yr",
    "Capacity with Modification Time 10+ yr",
    "File Count with Modification Time future",
    "Capacity with Modification Time future",
  ],
  Created: [
    "File Count with Creation Time 0-1 wk",
    "Capacity with Creation Time 0-1 wk",
    "File Count with Creation Time 1 wk - 1 mo",
    "Capacity with Creation Time 1 wk - 1 mo",
    "File Count with Creation Time 1-3 mo",
    "Capacity with Creation Time 1-3 mo",
    "File Count with Creation Time 3-6 mo",
    "Capacity with Creation Time 3-6 mo",
    "File Count with Creation Time 6-12 mo",
    "Capacity with Creation Time 6-12 mo",
    "File Count with Creation Time 1-2 yr",
    "Capacity with Creation Time 1-2 yr",
    "File Count with Creation Time 2-3 yr",
    "Capacity with Creation Time 2-3 yr",
    "File Count with Creation Time 3-4 yr",
    "Capacity with Creation Time 3-4 yr",
    "File Count with Creation Time 4-5 yr",
    "Capacity with Creation Time 4-5 yr",
    "File Count with Creation Time 5-6 yr",
    "Capacity with Creation Time 5-6 yr",
    "File Count with Creation Time 6-7 yr",
    "Capacity with Creation Time 6-7 yr",
    "File Count with Creation Time 7-8 yr",
    "Capacity with Creation Time 7-8 yr",
    "File Count with Creation Time 8-9 yr",
    "Capacity with Creation Time 8-9 yr",
    "File Count with Creation Time 9-10 yr",
    "Capacity with Creation Time 9-10 yr",
    "File Count with Creation Time 10+ yr",
    "Capacity with Creation Time 10+ yr",
    "File Count with Creation Time future",
    "Capacity with Creation Time future",
  ],
  "Access Time": [
    "File Count with Access Time 0-1 wk",
    "Capacity with Access Time 0-1 wk",
    "File Count with Access Time 1 wk - 1 mo",
    "Capacity with Access Time 1 wk - 1 mo",
    "File Count with Access Time 1-3 mo",
    "Capacity with Access Time 1-3 mo",
    "File Count with Access Time 3-6 mo",
    "Capacity with Access Time 3-6 mo",
    "File Count with Access Time 6-12 mo",
    "Capacity with Access Time 6-12 mo",
    "File Count with Access Time 1-2 yr",
    "Capacity with Access Time 1-2 yr",
    "File Count with Access Time 2-3 yr",
    "Capacity with Access Time 2-3 yr",
    "File Count with Access Time 3-4 yr",
    "Capacity with Access Time 3-4 yr",
    "File Count with Access Time 4-5 yr",
    "Capacity with Access Time 4-5 yr",
    "File Count with Access Time 5-6 yr",
    "Capacity with Access Time 5-6 yr",
    "File Count with Access Time 6-7 yr",
    "Capacity with Access Time 6-7 yr",
    "File Count with Access Time 7-8 yr",
    "Capacity with Access Time 7-8 yr",
    "File Count with Access Time 8-9 yr",
    "Capacity with Access Time 8-9 yr",
    "File Count with Access Time 9-10 yr",
    "Capacity with Access Time 9-10 yr",
    "File Count with Access Time 10+ yr",
    "Capacity with Access Time 10+ yr",
    "File Count with Access Time future",
    "Capacity with Access Time future",
  ],
  Biggest: [
    "Top 5 Longest File Names",
    "Top 5 Longest Directory Names",
    "Top 5 Longest File Path",
    "Top 5 Longest Directory Path",
    "Top 5 Biggest File Names",
    "Top 5 Biggest Directory With Count",
    "Top 5 Biggest Directory With Capacity",
  ],
};

export interface ReportEntry {
  category: string;
  sub_category?: string;
  value: number | string;
  valueType: ReportValueType;
}
