---
- name: 2.1. Update apt package index
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: 2.2. Ensure essential packages are installed
  apt:
    name:
      - nfs-common
      - smbclient
      - xmlstarlet
    state: present

# Disable ICMP redirects for security
- name: Disable ICMP redirects
  sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: yes
    sysctl_set: yes
  loop:
    # Disable sending of ICMP redirects
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
    # Disable acceptance of ICMP redirects
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects
    # Disable secure ICMP redirects
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects

- name: 2.3. Copy systemd service file for boot script
  become: yes
  template:
    src: ./templates/start-rpc-statd-service.j2
    dest: /etc/systemd/system/start-rpc-statd.service
    owner: root
    group: root
    mode: "0644"

- name: 2.4. Reload systemd daemon
  become: yes
  command: systemctl daemon-reload

- name: 2.5. Enable the start-rpc-statd service
  become: yes
  systemd:
    name: start-rpc-statd.service
    enabled: yes

- name: 2.6. Start the service
  become: yes
  systemd:
    name: start-rpc-statd.service
    state: started
  when: local_cluster is defined

- name: 2.7. Set the hostname
  command: hostnamectl set-hostname datamigrator

- name: Set recommended SSH ciphers
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Ciphers'
    line: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
    state: present
  notify: Restart SSH

- name: Set recommended SSH MACs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MACs'
    line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
    state: present
  notify: Restart SSH
