appName: "config-service"
kubeApiVersion: "apps/v1"
replicaCount: 1

image:
  repository: ndm-config-service

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/role: "datamigrator-role"
  vault.hashicorp.com/agent-inject-secret-postgres.env: "secrets/postgres-secrets/postgres-creds"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-template-postgres.env: |
    {{- with secret "secrets/postgres-secrets/postgres-creds" -}}
    export DB_USER="{{ .Data.POSTGRES_DMADMIN_USER }}"
    export DB_PASSWORD="{{ .Data.POSTGRES_DMADMIN_PASSWORD }}"
    {{- end }}

serviceAccountName: datamigrator-openbao-sa

args:
  - "--source-vault"

imagePullSecrets: azure-dev-acr-creds

env:
  - name: MY_HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: APP_PORT
    value: "3000"
  - name: APP_HOST
    value: "$(MY_HOST_IP)"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "datamigrator"
  - name: DB_HOST
    value: "postgresql.postgres.svc.cluster.local"

  # - name: DB_USER # from secret
  #   value: ""
  # - name: DB_PASSWORD # from secret
  #   value: ""

  - name: SCHEMA
    value: "datamigrator"
  - name: LOG_LEVEL
    value: "INFO"
  - name: LOG_DIR
    value: "/logs"
  - name: ENABLE_VERSIONS_FETCH
    value: "false"
  - name: ENABLE_PRE_LIST_PATH
    value: "false"
  - name: KEYCLOAK_BASE_URL
    value: "http://keycloak.keycloak.svc.cluster.local/keycloak"
  - name: KEYCLOAK_REALM
    value: "datamigrator"
  - name: TEMPORAL_ADDRESS
    value: "temporaltest-frontend.temporal.svc.cluster.local:7233"
  - name: SEND_EMAIL
    value: "http://admin-service-service:3000"
  - name: BUNDLE_OUTPUT_PATH
    value: "/generated-zips"
  - name: ISTIO_GATEWAY_TLS_SECRET
    value: "datamigrator-istio-tls"
  - name: ISTIO_NAMESPACE
    value: "istio-system"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

# ==============================
# Ingress for User-facing APIs
# ==============================
ingressThrottle:
  prefixPaths:
    - /api/v1/servers
    - /api/v1/paths-upload
    - /api/v1/support-bundle
  ingressClassName: public
  userDefinedAnnotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "25" # max 25 req/s per client
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "1" # 1 burst request allowed
  tls:
    enabled: false
  host: ""

# ==============================
# Ingress for CP and worker
# ==============================
ingress:
  # Use prefix matching - automatically matches all subpaths
  prefixPaths:
    - /api/v1/work-manager
    - /api/v1/config-docs
  ingressClassName: public
  userDefinedAnnotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    enabled: false
  host: ""

persistentVolumes:
  - name: generated-zips
    mountPath: /generated-zips
    hostPath: /generated-zips
