---
- name: 4.1. Ensure destination directories exist
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: yes
  loop:
    - { path: "/opt/datamigrator" }
    - { path: "/opt/datamigrator/bin" }
    - { path: "/opt/datamigrator/binary" }
    - { path: "/opt/datamigrator/conf" }
    - { path: "/opt/datamigrator/lock" }
    - { path: "/opt/datamigrator/logs" }
    - { path: "/mnt/datamigrator" }

- name: 4.1.1 Configure NDM Versions
  become: yes
  copy:
    content: |
      initial_version={{ build_version }}
      current_version={{ build_version }}
      previous_version=N/A
    dest: "/opt/datamigrator/conf/versions.conf"
    owner: root
    group: root

- name: 4.2. Copy binary file to remote server
  become: yes
  ansible.builtin.copy:
    src: "{{ local_binary_path }}"
    dest: "{{ remote_binary_path }}"
    mode: '0755'

- name: 4.3. Make the binary file executable
  become: yes
  ansible.builtin.file:
    path: "{{ remote_binary_path }}"
    mode: '0755'

- name: 4.4. Update systemd service file with the latest binary
  become: yes
  ansible.builtin.template:
    src: ./templates/worker.service.j2
    dest: /etc/systemd/system/datamigrator-worker.service
    owner: root
    group: root
    mode: '0644'

- name: 4.5. Copy worker-register.j2 to /opt/datamigrator/bin/
  become: yes
  template:
    src: ./templates/worker-register.j2
    dest: /opt/datamigrator/bin/worker_register.sh
    mode: '0755'
    owner: root
    group: root
  when: local_worker_update is not defined


- name: 4.6. Copy worker env to /opt/datamigrator/conf/
  become: yes
  copy:
    src: ./templates/worker.env.j2
    dest: /opt/datamigrator/conf/worker.env
    mode: '0644'
    owner: root
    group: root
  when: local_worker_update is not defined

- name: 4.7. Reload systemd daemon
  become: yes
  ansible.builtin.command: systemctl daemon-reload

- name: 4.8. Disable the datamigrator worker service from starting on boot
  become: yes
  ansible.builtin.systemd_service:
    name: datamigrator-worker.service
    enabled: false
    state: stopped
  when: local_worker_update is not defined

- name: 4.8.1. Restart worker service
  ansible.builtin.service:
    name: datamigrator-worker.service
    state: restarted
  when: local_worker_update is defined

- name: 4.8.2. Pause for 90 seconds to make sure worker is up
  ansible.builtin.pause:
    seconds: 90
  when: local_worker_update is defined

- name: 4.8.3. Print last 20 lines of the worker log
  ansible.builtin.command:
    cmd: tail -n 20 /opt/datamigrator/logs/datamigrator-worker.log
  register: log_output
  when: local_worker_update is defined

- name: 4.8.4. Debug last 20 lines of the log
  ansible.builtin.debug:
    msg: "{{ log_output.stdout }}"
  when: local_worker_update is defined
