---
- name: Creates postgres directory
  become: yes
  file:
    path: $HOME/postgres
    state: directory

- name: generate random passwords for postgres
  become: yes
  shell: |
    export POSTGRES_ROOT_PASSWORD=$(kubectl exec -ti openbao-0 -n openbao -- bao kv get -format=json /secrets/postgres-secrets/postgres-creds | jq -r .data.POSTGRES_PASSWORD)
    export DMADMIN_PASSWORD=$(kubectl exec -ti openbao-0 -n openbao -- bao kv get -format=json /secrets/postgres-secrets/postgres-creds | jq -r .data.POSTGRES_DMADMIN_PASSWORD)
    export KEYCLOAK_POSTGRES_PASSWORD=$(kubectl exec -ti openbao-0 -n openbao -- bao kv get -format=json /secrets/postgres-secrets/postgres-creds | jq -r .data.KEYCLOAK_POSTGRES_PASSWORD)
    export LIQUIBASE_POSTGRES_PASSWORD=$(kubectl exec -ti openbao-0 -n openbao -- bao kv get -format=json /secrets/postgres-secrets/postgres-creds | jq -r .data.LIQUIBASE_POSTGRES_PASSWORD)
    export TEMPORAL_POSTGRES_PASSWORD=$(kubectl exec -ti openbao-0 -n openbao -- bao kv get -format=json /secrets/postgres-secrets/postgres-creds | jq -r .data.TEMPORAL_POSTGRES_PASSWORD)
    echo "ROOT_PASSWORD:$POSTGRES_ROOT_PASSWORD"
    echo "DMADMIN_PASSWORD:$DMADMIN_PASSWORD"
    echo "KEYCLOAK_POSTGRES_PASSWORD:$KEYCLOAK_POSTGRES_PASSWORD"
    echo "LIQUIBASE_POSTGRES_PASSWORD:$LIQUIBASE_POSTGRES_PASSWORD"
    echo "TEMPORAL_POSTGRES_PASSWORD:$TEMPORAL_POSTGRES_PASSWORD"
  args:
    executable: /bin/bash
  register: postgres_passwords

- name: Set Base64-encoded passwords as facts
  set_fact:
    postgres_root_password: "{{ (postgres_passwords.stdout_lines | select('match', 'ROOT_PASSWORD:.*') | map('regex_replace', 'ROOT_PASSWORD:(.*)', '\\1') | list | first) }}"
    postgres_root_password_base64: "{{ (postgres_passwords.stdout_lines | select('match', 'ROOT_PASSWORD:.*') | map('regex_replace', 'ROOT_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"
    dmadmin_password: "{{ (postgres_passwords.stdout_lines | select('match', 'DMADMIN_PASSWORD:.*') | map('regex_replace', 'DMADMIN_PASSWORD:(.*)', '\\1') | list | first) }}"
    dmadmin_password_base64: "{{ (postgres_passwords.stdout_lines | select('match', 'DMADMIN_PASSWORD:.*') | map('regex_replace', 'DMADMIN_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"
    keycloak_postgres_password: "{{ (postgres_passwords.stdout_lines | select('match', 'KEYCLOAK_POSTGRES_PASSWORD:.*') | map('regex_replace', 'KEYCLOAK_POSTGRES_PASSWORD:(.*)', '\\1') | list | first) }}"
    keycloak_postgres_password_base64: "{{ (postgres_passwords.stdout_lines | select('match', 'KEYCLOAK_POSTGRES_PASSWORD:.*') | map('regex_replace', 'KEYCLOAK_POSTGRES_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"
    liquibase_postgres_password: "{{ (postgres_passwords.stdout_lines | select('match', 'LIQUIBASE_POSTGRES_PASSWORD:.*') | map('regex_replace', 'LIQUIBASE_POSTGRES_PASSWORD:(.*)', '\\1') | list | first) }}"
    liquibase_postgres_password_base64: "{{ (postgres_passwords.stdout_lines | select('match', 'LIQUIBASE_POSTGRES_PASSWORD:.*') | map('regex_replace', 'LIQUIBASE_POSTGRES_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"
    temporal_postgres_password: "{{ (postgres_passwords.stdout_lines | select('match', 'TEMPORAL_POSTGRES_PASSWORD:.*') | map('regex_replace', 'TEMPORAL_POSTGRES_PASSWORD:(.*)', '\\1') | list | first) }}"
    temporal_postgres_password_base64: "{{ (postgres_passwords.stdout_lines | select('match', 'TEMPORAL_POSTGRES_PASSWORD:.*') | map('regex_replace', 'TEMPORAL_POSTGRES_PASSWORD:(.*)', '\\1') | list | first) | b64encode }}"

- name: postgres-namespace template
  become: yes
  template: src=./templates/postgres-namespace.j2 dest=$HOME/postgres/postgres-namespace.yaml

- name: postgres-storageclass template
  become: yes
  template: src=./templates/postgres-storageclass.j2 dest=$HOME/postgres/postgres-storageclass.yaml

- name: postgres-primary-pv template
  become: yes
  template: src=./templates/postgres-primary-pv.j2 dest=$HOME/postgres/postgres-primary-pv.yaml

- name: postgres config map template
  become: yes
  template: src=./templates/postgres-configmap.j2 dest=$HOME/postgres/postgres-configmap.yaml

- name: postgres-secret template
  become: yes
  template: src=./templates/postgres-secret.j2 dest=$HOME/postgres/postgres-secret.yaml

- name: postgres-values template
  become: yes
  template: src=./templates/postgres-values.j2 dest=$HOME/postgres/postgres-values.yaml

- name: Cleanup service account
  become: yes
  shell: |
    kubectl delete serviceaccount -n postgres postgres-sa
  when: postgres_uninstall is defined

- name: remove previous installation
  become: yes
  shell: |
    helm delete postgresql --namespace "postgres"
    kubectl delete pvc --all --namespace "postgres"
    kubectl delete -f $HOME/postgres/postgres-configmap.yaml
    kubectl delete -f $HOME/postgres/postgres-primary-pv.yaml
    kubectl delete -f $HOME/postgres/postgres-storageclass.yaml
    kubectl delete -f $HOME/postgres/postgres-secret.yaml
    kubectl delete -f $HOME/postgres/postgres-exporter.yaml
    kubectl delete -f $HOME/postgres/postgres-namespace.yaml
  when: postgres_uninstall is defined
  args:
    chdir: $HOME

- name: setup namespace, persistentvolume for postgres
  become: yes
  shell: |
    kubectl apply -f $HOME/postgres/postgres-namespace.yaml
    kubectl apply -f $HOME/postgres/postgres-storageclass.yaml
    kubectl apply -f $HOME/postgres/postgres-primary-pv.yaml
    kubectl apply -f $HOME/postgres/postgres-configmap.yaml
    kubectl apply -f $HOME/postgres/postgres-secret.yaml
  args:
    chdir: $HOME

- name: Create service account
  become: yes
  shell: |
    kubectl create serviceaccount -n postgres postgres-sa

- name: Deploy postgres helm chart
  become: yes
  shell: |

    helm upgrade --install postgresql oci://registry-1.docker.io/bitnamicharts/postgresql -f $HOME/postgres/postgres-values.yaml --version "{{ postgres_version }}" --namespace "postgres"
    exit 0
  args:
    executable: /bin/bash
  register: SHELL_STDOUT

- name: debug output
  ansible.builtin.debug:
    msg: "Helm Install (postgres): stderr: {{ SHELL_STDOUT.stderr_lines }} stdout: {{ SHELL_STDOUT.stdout_lines }}"

- name: Wait for 20 seconds before waiting for pods to come up
  ansible.builtin.pause:
    seconds: 20

- name: wait for pods to come up
  become: yes
  shell: kubectl wait --namespace="postgres" --for=condition=Ready pod --all
  register: kubectl_get_pods
  retries: 10
  delay: 25
  until: kubectl_get_pods.rc == 0

- name: debug output
  ansible.builtin.debug:
    msg: "Get pods (postgres): {{ kubectl_get_pods.stdout | split('\n') }}"

- name: Check postgres pod status
  shell: kubectl get pods -n postgres
  register: pod_status

- debug:
    var: pod_status.stdout

- name: postgres-exporter template
  become: yes
  template:
    src: ./templates/postgres-exporter.j2
    dest: $HOME/postgres/postgres-exporter.yaml

- name: Deploy postgres-exporter manifests
  become: yes
  shell: |
    kubectl apply -f $HOME/postgres/postgres-exporter.yaml
  args:
    chdir: $HOME

- name: Delete postgres directory
  become: yes
  file:
    path: $HOME/postgres
    state: absent
