export enum SmbErrors {
    ACCESS_DENIED = 'NT_STATUS_ACCESS_DENIED',
    CONNECTION_REFUSED = 'NT_STATUS_CONNECTION_REFUSED',
    LOGON_FAILURE = 'NT_STATUS_LOGON_FAILURE',
    TIMEOUT='NT_STATUS_IO_TIMEOUT'
}
