appName: "admin-service"
kubeApiVersion: "apps/v1"
replicaCount: 1

image:
  repository: ndm-admin-service

annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/role: "datamigrator-role"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-inject-secret-keycloak.env: "secrets/keycloak-secrets/keycloak-creds"
  vault.hashicorp.com/agent-inject-secret-postgres.env: "secrets/postgres-secrets/postgres-creds"
  vault.hashicorp.com/agent-inject-secret-redis.env: "secrets/redis-secrets/redis-creds"
  vault.hashicorp.com/agent-inject-template-keycloak.env: |
    {{- with secret "secrets/keycloak-secrets/keycloak-creds" -}}
    export KEYCLOAK_CLIENT_SECRET="{{ .Data.KEYCLOAK_CLIENT_SECRET }}"
    export KEYCLOAK_ADMIN_USERNAME="{{ .Data.KEYCLOAK_ADMIN_USER }}"
    export KEYCLOAK_ADMIN_PASSWORD="{{ .Data.KEYCLOAK_ADMIN_PASSWORD }}"
    {{- end }}
  vault.hashicorp.com/agent-inject-template-postgres.env: |
    {{- with secret "secrets/postgres-secrets/postgres-creds" -}}
    export DATABASE_USERNAME="{{ .Data.POSTGRES_DMADMIN_USER }}"
    export DATABASE_PASSWORD="{{ .Data.POSTGRES_DMADMIN_PASSWORD }}"
    {{- end }}
  vault.hashicorp.com/agent-inject-template-redis.env: |
    {{- with secret "secrets/redis-secrets/redis-creds" -}}
    export REDIS_USERNAME="{{ .Data.REDIS_USERNAME }}"
    export REDIS_PASSWORD="{{ .Data.REDIS_PASSWORD }}"
    {{- end }}

serviceAccountName: datamigrator-openbao-sa
args:
  - "--source-vault"

imagePullSecrets: azure-dev-acr-creds

persistentVolumes:
  - name: upgrade
    mountPath: /upgrade
    hostPath: /upgrade

env:
  - name: MY_HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: DATABASE_HOST
    value: "postgresql.postgres.svc.cluster.local"
  - name: DATABASE_PORT
    value: "5432"
  - name: REDIS_HOST
    value: "redis-master.redis.svc.cluster.local"
  - name: REDIS_EXTERNAL_HOST
    value: "$(MY_HOST_IP)"
  - name: REDIS_EXTERNAL_PORT
    value: "30379"

  # - name: DATABASE_USERNAME # from secret
  #   value: "dmadmin"
  # - name: DATABASE_PASSWORD # from secret
  #   value: "dmadmin"
  # - name: KEYCLOAK_CLIENT_SECRET # from secret
  #   value: "123"
  # - name: KEYCLOAK_ADMIN_USERNAME # from secret
  #   value: "admin"
  # - name: KEYCLOAK_ADMIN_PASSWORD # from secret
  #   value: "admin"

  - name: KEYCLOAK_ADMIN_CLIENT
    value: "admin-cli"
  - name: DATABASE_NAME
    value: "datamigrator"
  - name: DATABASE_SCHEMA
    value: "datamigrator"
  - name: DATABASE_TYPE
    value: "postgres"
  - name: AUTOLOAD_ENTITIES
    value: "true"
  - name: SYNCHRONIZE
    value: "false"
  - name: KEYCLOAK_BASE_URL
    value: "http://keycloak.keycloak.svc.cluster.local/keycloak"
  - name: SWAGGER_BASEURL
    value: "https://$(MY_HOST_IP)"
  - name: KEYCLOAK_REALM
    value: "datamigrator"
  - name: KEYCLOAK_CLIENT_ID
    value: "datamigrator-client"
  - name: NODE_TLS_REJECT_UNAUTHORIZED
    value: "0"
  - name: ENABLE_VERSIONS_FETCH
    value: "false"
  - name: ENABLE_PRE_LIST_PATH
    value: "false"
  - name: LOG_LEVEL
    value: "INFO"
  - name: LOG_DIR
    value: "/logs"
  - name: CONTROL_PLANE_IP
    value: "$(MY_HOST_IP)"
  - name: PROMETHEUS_BASE_URL
    value: "http://prometheus-server.prometheus.svc.cluster.local:80/api/v1"
  - name: UPLOAD_PATH
    value: "/upgrade"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

# ==============================
# Ingress for User-facing APIs
# ==============================
ingressThrottle:
  prefixPaths:
    - /api/v1/accounts
    - /api/v1/user-status
    - /api/v1/reset-password
    - /api/v1/create-user
    - /api/v1/user-roles
    - /api/v1/user-permissions
    - /api/v1/roles
    - /api/v1/users
    - /api/v1/projects
    - /api/v1/setting
    - /api/v1/about-ndm
  ingressClassName: public
  userDefinedAnnotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "25" # max 25 req/s per client
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "1" # 1 burst request allowed
  tls:
    enabled: false
  host: ""

# ==============================
# Ingress for CP and worker
# ==============================
ingress:
  prefixPaths:
    - /api/v1/health
    - /api/v1/admin-docs
    - /api/v1/inviteUser
    - /api/v1/email
    - /api/v1/worker-registration
    - /api/v1/secrets
    - /api/v1/upgrade
  ingressClassName: public
  userDefinedAnnotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    enabled: false
  host: ""
