name: Black Duck SCA Scan

on:
  push:
    branches: [main, sm/bd-action-workflow]
  pull_request:
    branches: [main, sm/bd-action-workflow]
  workflow_dispatch:

env:
  BLACKDUCK_URL: https://blackduck.eng.netapp.com
  SERVICE_NAME: admin-service
  SERVICE_PATH: services/admin-service
  PROJECT_NAME: Test_NDM
  VERSION_NAME: test_v
  BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

jobs:
  Black-Duck-SCA-Scan:
    name: Black Duck SCA Scan
    runs-on: openlab

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (required for Black Duck Detect)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Print debug variables
        run: |
          echo "PROJECT_NAME -->  $PROJECT_NAME"
          echo "Running on -->  $RUNNER_OS"
          echo "Service Name -->  $SERVICE_NAME"
          echo "Service Path -->  $SERVICE_PATH"
          echo "Project Version -->  $VERSION_NAME"
          echo "Black Duck URL -->  $BLACKDUCK_URL"
          echo "Workspace -->  ${{ github.workspace }}"
          echo "$BLACKDUCK_API_TOKEN"

      - name: Run Black Duck Detect
        shell: bash
        env:
          BLACKDUCK_API_TOKEN: "$BLACKDUCK_API_TOKEN"
        run: |
          if [ -z "$BLACKDUCK_API_TOKEN" ]; then
            echo "❌ BLACKDUCK_API_TOKEN is not set. Please provide it via GitHub Secrets or act --secret-file."
            exit 1
          fi

          curl -s https://detect.blackduck.com/detect10.sh -o detect10.sh
          chmod +x detect10.sh
          echo "-------------------"
          echo pwd
          echo "-------------------"

          ./detect10.sh \
            --detect.project.name="$PROJECT_NAME" \
            --blackduck.url=https://blackduck.eng.netapp.com \
            --blackduck.api.token="$BLACKDUCK_API_TOKEN" \
            --detect.project.version.name="$VERSION_NAME" \
            --detect.cleanup=false \
            --detect.source.path=services/admin-service \ 
            --detect.code.location.name="Test_NDM_${{ github.run_id }}" \
            --detect.accuracy.required=NONE
            --detect.tools=DETECTOR,SIGNATURE_SCAN \
            --detect.detector.search.depth=50 \
            --detect.detector.search.continue=true \
            --blackduck.trust.cert=true \
            --blackduck.offline.mode=false
