name: Build and Push to ACR on PR Merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  determine-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      matrix_count: ${{ steps.set-matrix.outputs.matrix_count }}
    steps:
      - name: Checkout Code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: set-matrix
        shell: bash
        run: |
          # List of all known service directories
          services=( "db-writer" "keycloak-customizations" "reports-service" "admin-service" "config-service" "datamigrator-ui" "jobs-service" "liquibase" )

          # Convert changed_services array to JSON on a single line using jq
          service_json=$(printf '%s\n' "${services[@]}" | jq -R . | jq -s . | tr -d '\n')
          echo "Matrix for changed services: $service_json"

          # Write outputs ensuring the JSON is on one line
          echo "matrix={\"service\":$service_json}" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: determine-matrix
    strategy:
      matrix:
        service: ${{ fromJson(needs.determine-matrix.outputs.matrix).service }}
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Authenticate to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_SP_USERNAME }}
          password: ${{ secrets.AZURE_SP_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image for ${{ matrix.service }}
        run: |
          echo "Building Docker image for service: ${{ matrix.service }}"
          IMAGE_NAME="${{ secrets.ACR_NAME }}.azurecr.io/ndm-${{ matrix.service }}"
          echo "Using image tags:"
          echo "$IMAGE_NAME:${{ github.sha }}"
          echo "$IMAGE_NAME:latest"

          if [ "${{ matrix.service }}" = "liquibase" ]; then
            CONTEXT="liquibase"
          else
            CONTEXT="services/${{ matrix.service }}"
          fi

          docker buildx build --platform linux/amd64,linux/arm64 --secret id=git_token,env=GITOPS_USER_GITHUB_TOKEN \
            -t "$IMAGE_NAME:${{ github.sha }}" \
            -t "$IMAGE_NAME:latest" \
            --push "$CONTEXT"
        env:
          GITOPS_USER_GITHUB_TOKEN: ${{ secrets.GITOPS_USER_GITHUB_TOKEN }}
          DOCKER_BUILDKIT: 1
