name: Build and Push to ACR on PR Merge

on:
  push:
    branches:
      - main
      - temporal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Replace GitHub Token Placeholder in .npmrc
      - name: Replace GitHub Token Placeholder in .npmrc
        run: |
          sed -i 's|${GITOPS_USER_GITHUB_TOKEN}|${{ secrets.GITOPS_USER_GITHUB_TOKEN }}|' .npmrc

      # Authenticate to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry
      - name: 'Build and push image'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_SP_USERNAME }}
          password: ${{ secrets.AZURE_SP_PASSWORD }}

      # Determine the tag suffix based on the branch
      - name: Set Tag Suffix
        id: set_tag_suffix
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/temporal" ]]; then
            echo "TAG_SUFFIX=-temporal" >> $GITHUB_ENV
          else
            echo "TAG_SUFFIX=" >> $GITHUB_ENV
          fi

      # Build the Docker image using commit hash and latest tag
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }}${{ env.TAG_SUFFIX }} .
          docker tag ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }}${{ env.TAG_SUFFIX }} ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:latest${{ env.TAG_SUFFIX }}

      # Push both the 'commit hash' and 'latest' tags
      - name: Push Docker Images
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:${{ github.sha }}${{ env.TAG_SUFFIX }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:latest${{ env.TAG_SUFFIX }}

  build-migrations:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to Azure Container Registry
      - name: 'Build and push image'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_SP_USERNAME }}
          password: ${{ secrets.AZURE_SP_PASSWORD }}

      # Determine the tag suffix based on the branch
      - name: Set Tag Suffix
        id: set_tag_suffix
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/temporal" ]]; then
            echo "TAG_SUFFIX=-temporal" >> $GITHUB_ENV
          else
            echo "TAG_SUFFIX=" >> $GITHUB_ENV
          fi
        
      # Build the Docker image using commit hash and latest tag
      - name: Build Docker Image for Migrations
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}-migrations:${{ github.sha }}${{ env.TAG_SUFFIX }} ./liquibase
          docker tag ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}-migrations:${{ github.sha }}${{ env.TAG_SUFFIX }} ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}-migrations:latest${{ env.TAG_SUFFIX }}

      # Push both the 'commit hash' and 'latest' tags
      - name: Push Docker Image for Migrations
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}-migrations:${{ github.sha }}${{ env.TAG_SUFFIX }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}-migrations:latest${{ env.TAG_SUFFIX }}