name: Check Code Coverage and Run Unit Test Cases

on:
  pull_request:
    branches:
      - main
      - 'release/**'
    paths:
      - 'services/admin-service/**'
      - 'services/config-service/**'
      - 'services/db-writer/**'
      - 'services/jobs-service/**'
      - 'services/reports-service/**'
      - 'services/worker/**'
      - 'services/support-service/**'

permissions:
  contents: read

jobs:
  determine-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      matrix_count: ${{ steps.set-matrix.outputs.matrix_count }}
    steps:
      - name: Checkout Code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set matrix for changed services
        id: set-matrix
        shell: bash
        run: |
          all_services=( "db-writer" "reports-service" "admin-service" "config-service" "jobs-service" "worker" "support-service" )

          base_branch="${{ github.event.pull_request.base.ref }}"
          git fetch origin "$base_branch"
          base_sha=$(git rev-parse origin/$base_branch)
          head_sha="${{ github.sha }}"
          affected_services=()
          for service in "${all_services[@]}"; do
            if git diff --name-only "$base_sha" "$head_sha" | grep -q "^services/$service/"; then
              affected_services+=("$service")
            fi
          done

          # Convert to JSON for matrix
          service_json=$(printf '%s\n' "${affected_services[@]}" | jq -R . | jq -s . | tr -d '\n')
          echo "Matrix for selected services: $service_json"
          echo "matrix={\"service\":$service_json}" >> $GITHUB_OUTPUT

  unit-test-cases-and-code-coverage:
    runs-on: ubuntu-latest
    needs: determine-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.determine-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Replace GitHub Token Placeholder in .npmrc
        working-directory: services/${{ matrix.service }}
        run: |
          sed -i 's|${GITOPS_USER_GITHUB_TOKEN}|${{ secrets.GITOPS_USER_GITHUB_TOKEN }}|' .npmrc

      - name: Install dependencies
        working-directory: services/${{ matrix.service }}
        run: npm install

      - name: Run test cases with code coverage
        working-directory: services/${{ matrix.service }}
        run: npm run test:coverage
        continue-on-error: true
        env:
          CI: true

      - name: Clone cicd-scripts repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/cicd-scripts
          token: ${{ secrets.GITOPS_USER_GITHUB_TOKEN }}
          path: cicd-scripts

      - name: Validate test cases and code coverage for ${{ matrix.service }}
        working-directory: services/${{ matrix.service }}
        run: |
          chmod +x ../../cicd-scripts/scripts/cicd/unit_test_cases_coverage.sh
          ../../cicd-scripts/scripts/cicd/unit_test_cases_coverage.sh