name: Publish NDM libs to Github Registry

env:
  SEMVER_VERSION: '7.7.2'

on:
  workflow_dispatch:
    inputs:
      lib_name:
        description: 'Select library to publish'
        required: true
        type: choice
        options:
          - auth-lib
          - jobs-lib
          - logger-lib
          - api-handler-lib
      version_to_publish:
        description: 'Select version to publish'
        required: true
        type: string

jobs:
  build:
    runs-on: openlab
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@NetApp-Cloud-DataMigrate'

      - name: Install semver
        run: npm install semver@${{ env.SEMVER_VERSION }}

      - name: Validate version
        run: |
          version="${{ github.event.inputs.version_to_publish }}"
          if ! npx semver "$version" > /dev/null; then
            echo "Provided version '$version' is not a valid semantic version."
            exit 1
          fi


      - name: Get latest published version from GitHub Packages
        id: get_latest
        run: |
          latest_version=$(curl -s -H "Authorization: token ${{ secrets.GITOPS_USER_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/orgs/NetApp-Cloud-DataMigrate/packages/npm/${{ github.event.inputs.lib_name }}/versions" \
            | jq -r '.[].name' \
            | sort -V \
            | tail -n 1)
          
          echo "Latest version is $latest_version"
          echo "latest=$latest_version" >> $GITHUB_OUTPUT

      - name: Compare with provided version
        run: |
          latest="${{ steps.get_latest.outputs.latest }}"
          new="${{ github.event.inputs.version_to_publish }}"

          echo "Validating: new=$new vs latest=$latest"

          if dpkg --compare-versions "$new" le "$latest"; then
            echo "Provided version $new is not greater than published $latest"
            exit 1
          fi

          echo "Version is valid"

      - name: Install dependencies
        working-directory: lib/${{ github.event.inputs.lib_name }}
        run: npm i && npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITOPS_USER_GITHUB_TOKEN }}

      - name: Update version in package.json
        working-directory: lib/${{ github.event.inputs.lib_name }}
        run: npm version --new-version ${{ github.event.inputs.version_to_publish }} --no-git-tag-version

      - name: Publish package
        working-directory: lib/${{ github.event.inputs.lib_name }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITOPS_USER_GITHUB_TOKEN }}

      - name: Generate package manifest metadata.json
        run: |
          cat <<EOF > metadata.json
          {
            "library": "${{ github.event.inputs.lib_name }}",
            "version": "${{ github.event.inputs.version_to_publish }}",
            "build_time": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "commit": "${GITHUB_SHA}",
            "short_commit": "${GITHUB_SHA::7}",
            "branch": "${GITHUB_REF_NAME}",
            "workflow": "${GITHUB_WORKFLOW}",
            "run_id": "${GITHUB_RUN_ID}",
            "run_number": "${GITHUB_RUN_NUMBER}",
            "repository": "${GITHUB_REPOSITORY}",
            "repository_owner": "${GITHUB_REPOSITORY_OWNER}",
            "published_by": "${{ github.actor }}"
          }
          EOF

      - name: Upload manifest to Artifactory
        env:
          NDM_NEXUS_USERNAME: ${{ secrets.NDM_NEXUS_USERNAME }}
          NDM_NEXUS_PASSWORD: ${{ secrets.NDM_NEXUS_PASSWORD }}
        run: |
          BUILD_TYPE="${{ github.event_name }}"
          LIB_NAME="${{ github.event.inputs.lib_name }}"
          VERSION="${{ github.event.inputs.version_to_publish }}"

          if [ "$BUILD_TYPE" = "workflow_dispatch" ]; then
            ARTIFACTORY_PATH="manifests/libs/adhoc/${LIB_NAME}/${VERSION}/metadata.json"
          fi

          curl --silent --show-error --fail --request PUT --upload-file metadata.json \
            "https://generic.repo.eng.netapp.com/artifactory/openlab-generic/cicd/ndm/${ARTIFACTORY_PATH}" \
            -u "${NDM_NEXUS_USERNAME}:${NDM_NEXUS_PASSWORD}"

      - name: Generate latest.json pointer
        run: |
          LIB_NAME="${{ github.event.inputs.lib_name }}"
          VERSION="${{ github.event.inputs.version_to_publish }}"
          COMMIT="${GITHUB_SHA}"
          SHORT_SHA="${GITHUB_SHA::7}"
          ISO_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          DATE=$(date -u +'%Y-%m-%d')
          METADATA_PATH="manifests/libs/adhoc/${LIB_NAME}/${VERSION}/metadata.json"

          cat <<EOF > latest.json
          {
            "library": "$LIB_NAME",
            "version": "$VERSION",
            "commit": "$COMMIT",
            "short_commit": "$SHORT_SHA",
            "date": "$DATE",
            "updated_at": "$ISO_TIME",
            "metadata_path": "$METADATA_PATH",
            "published_by": "${{ github.actor }}"
          }
          EOF

      - name: Upload latest.json pointer to Artifactory
        env:
          NDM_NEXUS_USERNAME: ${{ secrets.NDM_NEXUS_USERNAME }}
          NDM_NEXUS_PASSWORD: ${{ secrets.NDM_NEXUS_PASSWORD }}
        run: |
          LIB_NAME="${{ github.event.inputs.lib_name }}"
          LATEST_VERSION_PATH="manifests/libs/adhoc/${LIB_NAME}/latest.json"

          curl --silent --show-error --fail --request PUT --upload-file latest.json \
            "https://generic.repo.eng.netapp.com/artifactory/openlab-generic/cicd/ndm/${LATEST_VERSION_PATH}" \
            -u "${NDM_NEXUS_USERNAME}:${NDM_NEXUS_PASSWORD}"