name: Run E2E API Automation Tests for NDM on vSphere

env:
  GITOPS_USER_GITHUB_TOKEN: ${{ secrets.GITOPS_USER_GITHUB_TOKEN }}
  TERRAFORM_VERSION: 1.12.1
  GO_VERSION: 1.24.2
  NODE_VERSION: 22.15.0
on:
  workflow_dispatch:
    inputs:
      control_plane_template:
        description: 'OVF VM template name for control-plane'
        required: true
        type: string
      worker_template:
        description: 'OVF VM template name for worker'
        required: true
        type: string
  workflow_call: 
    inputs:
      control_plane_template:
        description: 'OVF VM template name for control-plane'
        required: true
        type: string
      worker_template:
        description: 'OVF VM template name for worker'
        required: true
        type: string

permissions: 
  contents: read

jobs:
  run-ndm-api-tests:
    name: Run E2E API Automation Tests for NDM
    runs-on: openlab
    outputs:
      control_plane_vm_ip_address: ${{ steps.deployment-info.outputs.control_plane_vm_ip_address }}
      worker_vm_ip_addresses: ${{ steps.deployment-info.outputs.worker_vm_ip_addresses }}
    env:
      NDM_VM_PORT: 22
      NFS_NDM_WORKERS_PORT: 22
      NFS_SOURCE_HOST_IP: ${{ secrets.TEST_AUTO_FILE_SERVER_SOURCE_IP }}
      NFS_DESTINATION_HOST_IP: ${{ secrets.TEST_AUTO_FILE_SERVER_DESTINATION_IP }}
      NDM_USERNAME: ${{ secrets.NDM_APP_USERNAME }}
      PASSWORD: ${{ secrets.NDM_APP_PASSWORD }}
      NFS_PROTOCOL_USERNAME: "Root"
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure Provider Credentials
        run: |
          mkdir -p $GITHUB_WORKSPACE/credentials

          echo "Setting VM credentials..."
          VM_USERNAME=$(echo "${{ secrets.NDM_SSH_USERNAME }}" | base64 --decode)
          VM_PASSWORD=$(echo "${{ secrets.NDM_SSH_PASSWORD }}" | base64 --decode)

          # Write to GITHUB_ENV
          echo "VM_USERNAME=$VM_USERNAME" >> $GITHUB_ENV
          echo "VM_PASSWORD=$VM_PASSWORD" >> $GITHUB_ENV
          echo "NDM_VM_USER_NAME=$VM_USERNAME" >> $GITHUB_ENV
          echo "NDM_VM_PASSWORD=$VM_PASSWORD" >> $GITHUB_ENV
          echo "NFS_NDM_WORKERS_USER_NAME=$VM_USERNAME" >> $GITHUB_ENV
          echo "NFS_NDM_WORKERS_PASSWORD=$VM_PASSWORD" >> $GITHUB_ENV
          

          echo "TF_VAR_vsphere_server=$(echo "${{ secrets.VSPHERE_SERVER }}" | base64 --decode)" >> $GITHUB_ENV
          echo "TF_VAR_vsphere_user=$(echo "${{ secrets.VSPHERE_USERNAME }}" | base64 --decode)" >> $GITHUB_ENV
          echo "TF_VAR_vsphere_password=$(echo "${{ secrets.VSPHERE_PASSWORD }}" | base64 --decode)" >> $GITHUB_ENV
          
          CONTROL_PLANE_TEMPLATE="${{ inputs.control_plane_template || github.event.inputs.control_plane_template }}"
          WORKER_TEMPLATE="${{ inputs.worker_template || github.event.inputs.worker_template }}"

          echo "TF_VAR_worker_ovf_template_name=$WORKER_TEMPLATE" >> $GITHUB_ENV
          echo "TF_VAR_control_plane_ovf_template_name=$CONTROL_PLANE_TEMPLATE" >> $GITHUB_ENV
          echo "TF_VAR_ssh_user=$VM_USERNAME" >> $GITHUB_ENV
          echo "TF_VAR_ssh_pass=$VM_PASSWORD" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: |
          cd app-deployment/terraform/vsphere/environments/api
          terraform init

      - name: Validate Terraform Configuration
        run: |
          cd app-deployment/terraform/vsphere/environments/api
          terraform validate

      - name: Create Terraform Plan
        run: |
          cd app-deployment/terraform/vsphere/environments/api
          terraform plan -out=tfplan

      - name: Apply Terraform Plan
        run: |
          cd app-deployment/terraform/vsphere/environments/api
          terraform apply -auto-approve tfplan

      - name: Extract Deployment Information
        id: deployment-info
        run: |
          cd app-deployment/terraform/vsphere/environments/api
          CONTROL_PLANE_IP=$(terraform output -raw control_plane_vm_ip_address)
          WORKER_IPS=$(terraform output -json worker_vm_ip_addresses | jq -c .)
          echo "control_plane_vm_ip_address=$CONTROL_PLANE_IP" >> $GITHUB_OUTPUT
          echo "worker_vm_ip_addresses=$WORKER_IPS" >> $GITHUB_OUTPUT
          echo "Control Plane IP: $CONTROL_PLANE_IP"
          echo "Worker IPs: $WORKER_IPS"

      - name: Set NDM_WORKERS_HOST env
        id: set-workers-host
        run: |
          cd app-deployment/terraform/vsphere/environments/api
          WORKER_IPS=$(terraform output -json worker_vm_ip_addresses | jq -r '.[]' | paste -sd, -)
          echo "NFS_NDM_WORKERS_HOST=$WORKER_IPS" >> $GITHUB_ENV

      - name: Set VM IP Address for API Tests
        run: |
          echo "JOB_SERVICE_URL=https://${{ steps.deployment-info.outputs.control_plane_vm_ip_address }}" >> $GITHUB_ENV
          echo "CONFIG_SERVICE_URL=https://${{ steps.deployment-info.outputs.control_plane_vm_ip_address }}" >> $GITHUB_ENV
          echo "ADMIN_SERVICE_URL=https://${{ steps.deployment-info.outputs.control_plane_vm_ip_address }}" >> $GITHUB_ENV
          echo "KEYCLOAK_IP=${{ steps.deployment-info.outputs.control_plane_vm_ip_address }}" >> $GITHUB_ENV
          echo "NDM_VM_HOST=${{ steps.deployment-info.outputs.control_plane_vm_ip_address }}" >> $GITHUB_ENV

      - name: Install sshpass
        run: |
          echo "Installing sshpass..."
          sudo apt-get update -qq
          sudo apt-get install -y sshpass
          echo "sshpass installed successfully."

      - name: Wait for Service Boot Setup to Complete
        run: |
          echo "Monitoring service boot setup on ${{ steps.deployment-info.outputs.control_plane_vm_ip_address }}..."
          
          # Ensure script is executable
          chmod +x ./app-deployment/scripts/service_check.sh
          
          # Run the service_check.sh script to wait for the microk8s-boot service to complete
          ./app-deployment/scripts/service_check.sh \
          "${{ steps.deployment-info.outputs.control_plane_vm_ip_address }}" \
          "$VM_USERNAME" \
          "$VM_PASSWORD"
          
          if [ $? -ne 0 ]; then
            echo "Service setup failed or timed out"
            exit 1
          fi
          
          echo "Service setup completed successfully"

      - name: Set up Go for API Tests
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: ${{ env.GO_VERSION }}

      
      - name: Install Ginkgo
        run: |
          cd ndm-api-tests
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          go get github.com/onsi/gomega/...
          go mod tidy
          echo "Ginkgo and Gomega installed successfully."

      - name: Run API Tests
        run: |
          cd ndm-api-tests
          ./run-automation.sh
        continue-on-error: true

      - name: Destroy Terraform Resources
        if: always()
        run: |
          cd app-deployment/terraform/vsphere/environments/api
          terraform destroy -auto-approve

      - name: Clean Up Temporary Files
        if: always()
        run: |
          rm -rf $GITHUB_WORKSPACE/credentials 2>/dev/null || true