---
- name: Copy Docker image tar file to target
  copy:
    src: "../../../artifacts/datamigrator-{{ build_version }}.tar"
    dest: "$HOME/datamigrator-images-{{ build_version }}.tar"
    mode: '0644'
  when: local_cluster is not defined

- name: Copy helm chart tgz file to target
  copy:
    src: "../../../artifacts/datamigrator-{{ build_version }}.tgz"
    dest: "$HOME/datamigrator-helmchart-{{ build_version }}.tgz"
  when: local_cluster is not defined

- name: Template each subchart's Chart.yaml
  become: no
  local_action:
    module: template
    src: "../roles/datamigrator/helm-chart/chart.service.j2"
    dest: "../roles/datamigrator/helm-chart/package/charts/{{ item }}/Chart.yaml"
  loop: "{{ chart_names }}"
  vars:
    service_name: "{{ item }}"
  when: local_cluster is defined

- name: Template umbrella chart's Chart.yaml
  become: no
  local_action:
    module: template
    src: "../roles/datamigrator/helm-chart/chart.j2"
    dest: "../roles/datamigrator/helm-chart/package/Chart.yaml"
  when: local_cluster is defined

- name: Package each subchart
  become: no
  local_action:
    module: command
    cmd: helm package ../roles/datamigrator/helm-chart/package/charts/{{ item }} --version {{ build_version }} --destination ../roles/datamigrator/helm-chart/package
  loop: "{{ chart_names }}"
  when: local_cluster is defined

- name: Template umbrella chart's values.yaml
  become: no
  local_action:
    module: template
    src: "../roles/datamigrator/helm-chart/values.j2"
    dest: "../roles/datamigrator/helm-chart/package/values.yaml"
  when: local_cluster is defined

- name: Update umbrella chart dependencies
  become: no
  local_action:
    module: command
    cmd: helm dependency update ../roles/datamigrator/helm-chart/package
  when: local_cluster is defined

- name: Show rendered values.yaml
  become: no
  local_action:
    module: shell
    cmd: cat ../roles/datamigrator/helm-chart/package/values.yaml
  register: rendered_values
  when: local_cluster is defined

- name: Debug rendered values.yaml
  debug:
    var: rendered_values.stdout
  when: local_cluster is defined

- name: Package the umbrella chart (with templated values.yaml and Chart.yaml)
  become: no
  local_action:
    module: command
    cmd: helm package ../roles/datamigrator/helm-chart/package --version {{ build_version }} -d ../roles/datamigrator/helm-chart/package
  when: local_cluster is defined

- name: Copy the tarball to the remote host
  become: yes
  copy:
    src: "../roles/datamigrator/helm-chart/package/datamigrator-{{ build_version }}.tgz"
    dest: "$HOME/helm-chart.tgz"
  when: local_cluster is defined

- name: Clean up rendered subchart Chart.yaml files
  become: no
  local_action:
    module: file
    path: "../roles/datamigrator/helm-chart/package/charts/{{ item }}/Chart.yaml"
    state: absent
  loop: "{{ chart_names }}"
  ignore_errors: yes
  when: local_cluster is defined

- name: Clean up umbrella chart Chart.yaml
  become: no
  local_action:
    module: file
    path: "../roles/datamigrator/helm-chart/package/Chart.yaml"
    state: absent
  ignore_errors: yes
  when: local_cluster is defined

- name: Clean up umbrella chart values.yaml
  become: no
  local_action:
    module: file
    path: "../roles/datamigrator/helm-chart/package/values.yaml"
    state: absent
  ignore_errors: yes
  when: local_cluster is defined

- name: Clean up packaged subcharts
  become: no
  local_action:
    module: file
    path: "../roles/datamigrator/helm-chart/package/{{ item }}-{{ build_version }}.tgz"
    state: absent
  loop: "{{ chart_names }}"
  ignore_errors: yes
  when: local_cluster is defined

- name: Clean up chart.lock file
  become: no
  local_action:
    module: file
    path: "../roles/datamigrator/helm-chart/package/chart.lock"
    state: absent
  ignore_errors: yes
  when: local_cluster is defined

- name: Install Helm chart
  become: yes
  shell: |
    helm upgrade --install datamigrator -n datamigrator $HOME/helm-chart.tgz
  register: helm_install_output
  when: local_cluster is defined

- name: Debug Helm install output
  debug:
    var: helm_install_output.stdout_lines
  when: local_cluster is defined

- name: Wait for pods to come up and handle failure
  block:
    - name: Wait for pods to come up
      become: yes
      shell: kubectl wait --namespace="datamigrator" --for=condition=Ready pod -l app.kubernetes.io/name=datamigrator
      register: kubectl_get_pods
      retries: 10
      delay: 25
      until: kubectl_get_pods.rc == 0
  rescue:
    - name: Fetch and display pod logs
      become: yes
      shell: |
        for pod in $(kubectl get pods -n datamigrator -o jsonpath='{.items[*].metadata.name}'); do
          echo "Logs for pod: $pod"
          kubectl logs -n datamigrator $pod --all-containers=true
          echo "----------------------------------------"
        done
      register: pod_logs
    - name: Display pod logs
      ansible.builtin.debug:
        msg: "{{ pod_logs.stdout }}"
    - name: Fail the play due to pod readiness failure
      fail:
        msg: "Pods did not become ready within the expected time frame."
  when: local_cluster is defined

- name: debug output
  ansible.builtin.debug:
    msg: "Get pods (datamigrator): {{ kubectl_get_pods.stdout | split('\n') }}"
  when: local_cluster is defined

- name: Check datamigrator pod status
  shell: kubectl get pods -n datamigrator
  register: pod_status
  when: local_cluster is defined

- name: Delete the tarball from the remote host
  become: yes
  file:
    path: $HOME/helm-chart.tgz
    state: absent
  when: local_cluster is defined

- name: Delete the local tarball
  become: no
  local_action:
    module: file
    path: "../roles/datamigrator/helm-chart/package/datamigrator-0.1.0.tgz"
    state: absent
  when: local_cluster is defined

- name: Delete the local values.yaml in package folder
  become: no
  local_action:
    module: file
    path: "../roles/datamigrator/helm-chart/package/values.yaml"
    state: absent
  when: local_cluster is defined